### ISSUE TITLE
[FEATURE REQ] Provide access to x-ms-ratelimit headers

### ISSUE THREAD

**Issue by slomo** [Azure/azure-libraries-for-java#1001]
**Is your feature request related to a problem? Please describe.**

I am currently writing an component to monitor resource creation in my subscription. There is a trade of, when setting the interval for the monitoring calls between freshness and the number of requests that I can do before rate limiting starts to kick in. I could increase my interval, if I am closer to the limit, but in order for that to work I would require to get the remaining requests. When using the rest api directly I could rely on on the x-ms-ratelimit header, but I would rather like to use the java client.

**Describe the solution you'd like**

My problem would be easily solved if I could get access to the ratelimit header. They don't have to be returned as an result of the query. If there would be some registry where they are accounted or some stream that delivers them as they are received this would be totally fine.

**Describe alternatives you've considered**

Using the REST api beacuse the headers than would be available. If the java api would have som middleware to inspect requests I could built the functionality by myself.

**Additional context**

N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by yaohaizh** [comment]
@slomo you can interceptor the header like this: https://github.com/Azure/azure-libraries-for-java/blob/7fd501fe985cebf9c26de6ac70e185e4305064d4/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/ResourceManagerThrottlingInterceptor.java

You need register                 .withInterceptor(new ResourceManagerThrottlingInterceptor()) to configure your azure client.

**Comment by slomo** [comment]
Works like a charm.
