### ISSUE TITLE
[FEATURE REQ] Add BeginCreateAsync and BeginApplyAsync in Fluent API of selected services

### ISSUE THREAD

**Issue by ChenTanyi** [Azure/azure-libraries-for-java#1007]
As https://github.com/Azure/azure-libraries-for-java/issues/710, https://github.com/Azure/azure-libraries-for-net/issues/545 said, sometimes we don't need to wait for the creation or update result.
The lite has function named Begin***, but the Fluent API doesn't have, we need these API to achieve this scenario.

**Comment by yungezz** [comment]
on specific services with really long running operation: cosmos, aks.

**Comment by weidongxu-microsoft** [comment]
Done for common resource on resources/compute/network.
