### ISSUE TITLE
Request: Allow the use of custom data when launching a VM and attaching an OS disk

### ISSUE THREAD

**Issue by vincentdo** [Azure/azure-libraries-for-java#1038]
It seems strange that custom data is only supported when we're launching the OS disk as part of the VM creation request chain and not if we create the OS disk before hand. It seems like under the hood, Azure is launching the OS disk and then attaching it to the VM after anyway?

**Comment by yaohaizh** [comment]
@vincentdo this is old issue as the SDK have many changes. If you still on this, please use the latest SDk version. I'm closing this issue now. Feel free to re-open the issue if it still persists.
