### ISSUE TITLE
[FEATURE REQ] Need add Content-Type and Accept in HTTP Headers for V2-generator

### ISSUE THREAD

**Issue by ChenTanyi** [Azure/azure-libraries-for-java#1058]
Problem:
* Some services return 415 for default content-type, need to change request content-type into "application/json; charset=utf-8".
* Some services return xml as default. Accept Header could be change into "application/json, */*;q=0.8"

**Comment by weidongxu-microsoft** [comment]
Fixed in generator v4_fluentgen.
