### ISSUE TITLE
[FEATURE REQ] Context support for all APIs

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-libraries-for-java#1090]

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you pls help to add more info of the request? is it to provide interface for user to set UserAgent to ARM call? thanks.

**Comment by weidongxu-microsoft** [comment]
@yaohaizh 
@ChenTanyi 

Immediate use cast is for UserAgentPolicy for tracking.

Remote use case is for user to add arbitrary data into http pipeline context when start mgmt task, and then access them in HttpPipelinePolicy.

**Comment by weidongxu-microsoft** [comment]
Relate to https://github.com/Azure/azure-sdk-for-java/issues/9762

**Comment by weidongxu-microsoft** [comment]
Done in core-mgmt
https://github.com/Azure/azure-sdk-for-java/pull/13641

Pending for mgmt code and generator.
