### ISSUE TITLE
[FEATURE REQ] Migrate DeletegateTokenCredentails 

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-libraries-for-java#1092]
In V1, there is a DelegateTokenCredentials. We might support it on V2. Need close look into the problem.

**Comment by yungezz** [comment]
hi @yaohaizh is the DelegateTokenCredentials be scope of azure-identity or azure core, or fluent has its own tokenCredential interface?

**Comment by yaohaizh** [comment]
Not sure, I just see this on v1 runtime. @jianghaolu could have more input for this.

**Comment by xccc-msft** [comment]
Azure Identity has [AuthorizationCodeCredential](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/src/main/java/com/azure/identity/AuthorizationCodeCredential.java) with `redirectUri` and `authCode` aligning to `DeletegateTokenCredentails` in [track 1](https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md#oauth-2-for-web-apps)

**Comment by yungezz** [comment]
thanks @xccc-msft so we'll rely on `TokenCredential` from azure.identity to take care of it.
