### ISSUE TITLE
[BUG] azure-mgmt-resources test-jar not published

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-libraries-for-java#1094]
SDK libraries depends on it. Without that test-jar, SDK libraries can only run compile phase, it will fail on test or package phase.

```
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-mgmt-resources</artifactId>
            <version>1.31.1</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
```

**Comment by weidongxu-microsoft** [comment]
Ann Meng from Docs team reported this. It likely need to be solved before next release.

**Comment by nickzhums** [comment]
Thanks, we need this for the new Java doc generation pipeline
