### ISSUE TITLE
withParameters not working properly

### ISSUE THREAD

**Issue by assafmendelson** [Azure/azure-libraries-for-java#110]
While trying to deploy from a template as follows:

```
azure.deployments().define(deploymentName)
                    .withExistingResourceGroup(rgName)
                    .withTemplate(templateJson)
                    .withParameters(parameters)
                    .withMode(DeploymentMode.INCREMENTAL)
                    .beginCreate();
```

I get an error:
`
The request content was invalid and could not be deserialized: 'Error converting value \\\"https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#\\\" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition'. Path 'properties.parameters.$schema', line 1, position 4272.'.\"}}
`

When doing the same with withParametersLink and withTemplateLink (with the same template) everything works.

**Comment by jianghaolu** [comment]
`withTemplate()` and `withParameters()` takes a JSON object or a serialized JSON string. If you have a URL you need to use `withParametersLink()`. If you have a local file you need to read it into a string first.

**Comment by hovsepm** [comment]
Issue addressed.

**Comment by zuojihong** [comment]
I had the same issue as well. I did read the text of parameters.json into String but it still failed. Below is the code snippet:

           ```
            String templateJson = new String(Files.readAllBytes(Paths.get(templateUrl)), StandardCharsets.UTF_8);
            String parametersJson = new String(Files.readAllBytes(Paths.get(parametersUrl)), StandardCharsets.UTF_8);

            azureDeployment = azure.deployments().define(deploymentName)
                .withExistingResourceGroup(resourceGroup)
                .withTemplate(templateJson)
                .withParameters(parametersJson)
                .withMode(DeploymentMode.INCREMENTAL)
                .beginCreate();
```

The similar error was returned as below:

Status code 400, {"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: 'Error converting value \"https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#\" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition'. Path 'properties.parameters.$schema', line 1, position 6797.'."}}

I suggest to take a closer look into the issue.

**Comment by nakhanha** [comment]
What is the solution for this issue ?

Hi,
I am facing same error . withParameterLink works fine.

 Message=The request content was invalid and could not be deserialized: 'Error converting value "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition'. Path 'properties.parameters.$schema', line 8, position 100.'.
  Source=Microsoft.Azure.Management.ResourceManager.Fluent
  StackTrace:

**Comment by jahknow** [comment]
Hi,

I was facing the same problem but i found a solution to it from this link

https://github.com/Azure/azure-sdk-for-python/issues/482#issuecomment-581087316
