### ISSUE TITLE
[FEATURE REQ] Fix etag generation 

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-libraries-for-java#1105]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

Might be a generation problem, but currently fluent code doesn't handle them yet. 

References: 

https://github.com/Azure/azure-sdk/issues/706

**Comment by yungezz** [comment]
HI @xccc-msft  could you pls look at how to handle etag by following the guideline when working on DNS? thanks. Etag should be a common consistent among all services.
