### ISSUE TITLE
[FEATURE REQ] Follow track V2 SDK guidlines

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-libraries-for-java#1107]
Might revisit fluent lib for the following guidelines: 
- https://github.com/Azure/azure-sdk/pull/968/files
- https://github.com/Azure/azure-sdk/issues/673
- https://github.com/Azure/azure-sdk/issues/671

**Comment by weidongxu-microsoft** [comment]
For `Details` and `Options`, I assume it applies to client or handle written code.

`ApplicationId` is currently handled by UserAgentPolicy, and can be provided by `HttpLogOptions` in core.

`telemetry` might be mostly fine if we can support `Context` reasonably well. The core lib itself got some update but seems not used by any other data/client lib in sdk.

We probably need to register the namespace as https://azure.github.io/azure-sdk/general_design.html#namespaces
