### ISSUE TITLE
[FEATURE REQ] Normalize the exception handling 

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-libraries-for-java#1110]
There are predefined exception in azure core that would help normalize the exception to the end user. 

https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/core/azure-core/src/main/java/com/azure/core/exception

**Comment by weidongxu-microsoft** [comment]
Use `ManagementException` until azure-core update their code to support convert response body to `ManagementError`.
