### ISSUE TITLE
[FEATURE REQ] Support https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/identity/azure-identity

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-libraries-for-java#1111]
Go through azure identity for V2 authentication

**Comment by weidongxu-microsoft** [comment]
First is to make sure all auth that can be done in track1 should still be done in track2 (unit tests, or provide sample code). If indeed some auth is deprecated we need to document that (maybe still in AUTH.md).

Optional is to adopt new auth that provided by identity SDK. This can be done after preview.

**Comment by yungezz** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/9749
