### ISSUE TITLE
Database export 

### ISSUE THREAD

**Issue by JakubJecminek** [Azure/azure-libraries-for-java#112]
Hi,
is there method somewhere in com.microsoft.azure.management for export of azure sql database? 
We were unable to find any method for this except com.microsoft.azure.management.appservice.DatabaseBackupSetting which just specifies parameters.

We want to create backup of our azure database from our custom java application using your java library.

With best regards,
Jakub

**Comment by milismsft** [comment]
Exporting a database functionality will be available in the next release (tentatively end of February).

**Comment by milismsft** [comment]
@JakubJecminek https://github.com/Azure/azure-libraries-for-java/pull/196 adresses this missing feature.
