### ISSUE TITLE
[FEATURE REQ] Verify that major configure in azure core pipeline is inherited by other clients

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-libraries-for-java#1133]
E.g. proxy settings, connection settings, policies

E.g. inherit in graphrbac, key, secret, kudu

Best be done in unit tests.

**Comment by xccc-msft** [comment]
# azure-storage-blob
BlobServiceClientBuilder: `SqlDatabaseExportRequestImpl`, `ManageNetworkWatcher`, `ManageVpnGatewayVNet2VNetConnection`, `QueryMetricsAndActivityLogs`

BlobContainerClientBuilder: `ManageWebAppStorageAccountConnection`, `ManageLinuxWebAppStorageAccountConnection`, `QueryMetricsAndActivityLogs`

# azure-cosmos
CosmosClientBuilder: `CreateCosmosDBWithEventualConsistency`, `ManageHACosmosDB`

# azure-security-keyvault-keys
KeyClientBuilder: `VaultImpl`

# azure-security-keyvault-secrets
SecretClientBuilder: `VaultImpl`, `ManageWebAppCosmosDbByMsi`
