### ISSUE TITLE
[FEATURE REQ] Sync resources/graphrbac fix from track1

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-libraries-for-java#1136]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by yungezz** [comment]
pls help to list changes, thanks.

**Comment by ChenTanyi** [comment]
Resource: https://github.com/Azure/azure-libraries-for-java/commit/30dbcda9bcb8e681804d668eaeeeb959ecf80a3c
GraphRbac: https://github.com/Azure/azure-libraries-for-java/commit/181ffe21a76ade5bf792976a59dce02631b5ad4d
