### ISSUE TITLE
[FEATURE REQ] Deprecate getAccessProfile API in AKS V2

### ISSUE THREAD

**Issue by ChenTanyi** [Azure/azure-libraries-for-java#1144]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by yungezz** [comment]
This need to be addressed before AKS v2 preview. AKS is moved to p1 now.
