### ISSUE TITLE
[FEATURE REQ] Candidate items for migrate guide

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-libraries-for-java#1152]
Namespace mapping

Configure
https://github.com/Azure/azure-libraries-for-java/issues/1109
https://github.com/Azure/azure-libraries-for-java/issues/1127

Authenticate
https://github.com/Azure/azure-libraries-for-java/issues/1092
https://github.com/Azure/azure-libraries-for-java/issues/1111

Async (this would be where most incompatibility happens, because of switch from RxJava 1.x to Reactor)

Option to use PagedList for backward-compatibility from list interface https://github.com/Azure/azure-libraries-for-java/issues/1102

**Comment by yungezz** [comment]
hi @ChenTanyi could you pls share the sample? thanks
