### ISSUE TITLE
[FEATURE REQ] Check RequestIdPolicy

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-libraries-for-java#1165]
For `x-ms-client-request-id` header for tracing.

Track1
https://github.com/Azure/autorest-clientruntime-for-java/blob/master/client-runtime/src/main/java/com/microsoft/rest/RestClient.java#L261

**Comment by xccc-msft** [comment]
Provided [RequestIdPolicy](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/resources/mgmt/src/main/java/com/azure/management/resources/fluentcore/utils/HttpPipelineProvider.java#L67) as part of default built-in policies in track 2 scenario.
