### ISSUE TITLE
ISqlServers has no firewall option to allow access to Azure services

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-libraries-for-java#12]
_From @mloeffen on May 30, 2017 9:43_

The fluent api seems to have no option to allow Azure services to access the server. Sample code:
```cs
ISqlServer sqlServer = await azure.SqlServers
    .Define(this.sqlServerName)
    .WithRegion(Region.EuropeWest)
    .WithExistingResourceGroup(this.resourceGroupName)
    .WithAdministratorLogin(AdministratorLogin)
    .WithAdministratorPassword(administratorPassword)
    .WithNewFirewallRule(this.firewallRuleIpAddress)
    .WithFirewallAllowAccessToAzureServices(true) // <-- missing something like this
    .CreateAsync(token);
```

![2017-05-30 11_34_39-firewall settings - microsoft azure](https://cloud.githubusercontent.com/assets/986351/26577361/73a79ad6-452c-11e7-969a-211ecd98477d.png)

_Copied from original issue: Azure/azure-sdk-for-net#3296_

**Comment by martinsawicki** [comment]
a workaround has been provided so closing
