### ISSUE TITLE
[FEATURE REQ] Expose `outputResources` on `Deployment`

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [Azure/azure-libraries-for-java#1209]
The `Deployment` interface should expose the `outputResources` field documented on https://docs.microsoft.com/en-us/rest/api/resources/deployments/get#deploymentpropertiesextended.

This is useful, for example, if you want to remove all resources created by a deployment.

**Comment by weidongxu-microsoft** [comment]
Need upgrade resources to 2020-06-01
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json#L4756-L4764

The property does not exist in current 2019-08-01

**Comment by xccc-msft** [comment]
@dennis-benzinger-hybris We have PR ready for exposing outputResources. Please see [here](https://github.com/Azure/azure-libraries-for-java/pull/1237).
```java
List<ResourceReference> outputResources = deployment.outputResources();
```

**Comment by xccc-msft** [comment]
Close this as release in 1.36.0.
