### ISSUE TITLE
Azure Database Threat Detection Policies API available in SDK?

### ISSUE THREAD

**Issue by jatins** [Azure/azure-libraries-for-java#121]
I am interested in using this API:
https://docs.microsoft.com/en-us/rest/api/sql/databasethreatdetectionpolicies/get

Is this available via SDK?

Also, in _general_ what is a good way to figure out is a particular API is available in SDK. Currently, I press `Ctrl + Space` and judge from autocomplete suggestions which isn't very, umm, scientific.

**Comment by milismsft** [comment]
Hi @jatins, unfortunately this API is yet to be implemented; tentatively I will expect it to be available within the next two releases (end of March).

Regarding the second question, yes Ctrl+Space should give you a good indication of the available API's; also taking a look at the unit tests and the samples in the repo could be very useful (we try to have 100% test/sample coverage of the API surface we support). As for the new API will most likely be available via the SqlDatabase, "listThreatDetectionPolicies()" or "listThreatDetectionPolicies()".

**Comment by milismsft** [comment]
@jatins https://github.com/Azure/azure-libraries-for-java/pull/196 should address the missing feature.
