### ISSUE TITLE
[BUG] StorageAccount Allow Blob public access parameter not present in SDK

### ISSUE THREAD

**Issue by gergopapi2** [Azure/azure-libraries-for-java#1256]
I wanted to create a storage account via SDK (1.35.0) with parameter "Allow Blob public access" set to false. The default value is true so a false needs to be set explicitly. 

However, I could not find this parameter in the SDK. It is present in the REST api, in the ARM template, but not in the SDK. Please check my conversation with Microsoft Support (id: 120080621000570).

**Comment by weidongxu-microsoft** [comment]
@gergopapi2 
The `allowBlobPublicAccess` property is added on Jun 22.
https://github.com/Azure/azure-rest-api-specs/commit/80784443eefe04bf6f4d253f9f210044e6d432b1

The SDK has not yet to pick it up.

We will schedule it.

**Comment by weidongxu-microsoft** [comment]
Supported in https://github.com/Azure/azure-libraries-for-java/pull/1376

Will be included in next release (likely 1.40.1), scheduled in days.

**Comment by gergopapi2** [comment]
@weidongxu-microsoft  Thank you for the good news! Please let me know the SDK version when it is included.

**Comment by weidongxu-microsoft** [comment]
@gergopapi2 Version 1.41.0 released to maven.

For new project, it is recommended to use https://aka.ms/azsdk/java/mgmt, which will also have this feature in a few days (2.3.0).
