### ISSUE TITLE
Support user assigned identitites for AKS clusters

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [Azure/azure-libraries-for-java#1296]
The library should support creating AKS cluster with user assigned identities.

The relevant REST documentation is on:
https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate#managedclusteridentity

**Comment by weidongxu-microsoft** [comment]
@ChenTanyi Please help take a look.

**Comment by dennis-benzinger-hybris** [comment]
Do you have an ETA for this or will this feature be supported only in the "new style" SDK ?

**Comment by nickzhums** [comment]
@dennis-benzinger-hybris we are evaluating this and will let you know asap

**Comment by ChenTanyi** [comment]
@dennis-benzinger-hybris we would try to update the AKS and add this property before next release at Nov 27.

**Comment by dennis-benzinger-hybris** [comment]
That's great news. Thanks!

**Comment by ChenTanyi** [comment]
@dennis-benzinger-hybris After API updated, is it ok for you to use `inner` to assign identities? 

(Since currently the identity type doesn't support `SystenAssigned, UserAssigned`, I'm afraid it would be change later, which could cause some problem in current logic.)

**Comment by dennis-benzinger-hybris** [comment]
Yes, `inner` is ok for use. We already use it in a few other places.

**Comment by ChenTanyi** [comment]
@dennis-benzinger-hybris Thanks for confirm. It will be release at Nov 27.

After update, the identity will be in `ManagedClusterInner`, you can use `azure.kubernetesClusters().inner().beginCreateOrUpdate()`, or `kubernetesCluster.inner().withIdentity()` and then `kubernetesCluster.update().apply()`
