### ISSUE TITLE
[BUG] NullPointerException in VirtualMachineScaleSets list() operation

### ISSUE THREAD

**Issue by tsarna** [Azure/azure-libraries-for-java#1303]
**Describe the bug**

trying to list Virtual Machine Scale Sets that exists results in an NPE thrown from VirtualMachineScaleSetImpl:initializeChildrenFromInner, line 195, which is the first IF statement:

```
    protected void initializeChildrenFromInner() {
        this.extensions = new HashMap<>();
        if (this.inner().virtualMachineProfile().extensionProfile() != null) {
            if (this.inner().virtualMachineProfile().extensionProfile().extensions() != null) {
                for (VirtualMachineScaleSetExtensionInner inner : this.inner().virtualMachineProfile().extensionProfile().extensions()) {
                    this.extensions.put(inner.name(), new VirtualMachineScaleSetExtensionImpl(inner, this));
                }
            }
        }
    }
```

This means either `this.inner()` or `this.inner().virtualMachineProfile()` must be null, but I can't tell which from the stack trace and I was not able to debug in situ (observed in logs from a customer).

***Exception or Stack Trace***

The relevant section is:

```
java.lang.NullPointerException
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetInner.class
com.microsoft.azure.management.compute.implementation.VirtualMachineScaleSetImpl.initializeChildrenFromInner(VirtualMachineScaleSetImpl.java:195)
```

**To Reproduce**
It's not clear what data the Azure API is returning to cause this, nor under what circumstances it does this. I am not able to reproduce it on any of the subscriptions I have access to, I have only observed it in a customer's log file.

***Code Snippet***
Just calling `.list()` on a VirtualMachineScaleSets.

**Expected behavior**
The `list()` call should be tolerant of whatever it is that the REST API is returning in this case and return a list of scale sets and not fail in this case. It would be better to return VMSS instances with missing data (say, missing the VM profile, if that's the issue) or to skip the problem instances entirely than to fail completely, as currently there is no way to work around this failure so all functionality related to scale sets must be disabled in my application.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - JRE Version: OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode, sharing)
 - SDK Version: 1.30.0, but the code in question is identical in the current version.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@xccc-msft Please take a look.

**Comment by xccc-msft** [comment]
@tsarna Thanks for reporting this. I have created #1304 to fix this. Before we release new version, you may take below workaround
```java
computeManager.virtualMachineScaleSets().inner().list();
```
