### ISSUE TITLE
[QUERY] create a vm with managed boot diagnostics

### ISSUE THREAD

**Issue by erzads** [Azure/azure-libraries-for-java#1346]
**Query/Question**
How can I create a new vm with managed boot diagnostics enabled? 
The sdk has a method with no parameters to enable boot diagnostics but it ends up configuring it with a custom storage account, even thought there are overloaded method to inform a storage account. This makes me think this is a bug but I am not sure. 

***Why is this not a Bug or a feature Request?***
I am not sure if this is expected or not. 

**Setup (please complete the following information if applicable):**
 - JRE Version: [Open JDK 8]
 - SDK Version:  1.36.3 
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Query Added
- [ x] Setup information Added

**Comment by xccc-msft** [comment]
@erzads For the method without parameters, it would create storage account implicitly. The code for creating storage account with random name could be found [here](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java#L2754-L2766). The code to validate if storage account exists for boot diagnostics is [here](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java#L2770-L2796). Thanks.

**Comment by erzads** [comment]
Let me try to clarify it. How can I use the sdk such that when I check the boot diagnostics page in the portal I see this:
![IMG-20210121-WA0001](https://user-images.githubusercontent.com/699344/105351075-d3ced100-5bca-11eb-8e00-1207e01686ed.jpg)

I don't want to inform a storage account nor do I want it to create a random storage account.

**Comment by xccc-msft** [comment]
@erzads Do you mean you want to select `Disable` from SDK end?

**Comment by weidongxu-microsoft** [comment]
Add a `withBootDiagnosticsOnManagedStorageAccount` for this.

**Comment by weidongxu-microsoft** [comment]
1.40.0 released
