### ISSUE TITLE
[QUERY] Do the libraries depend on FabricIO8/kubernetes-client?

### ISSUE THREAD

**Issue by weiqingy** [Azure/azure-libraries-for-java#1377]
**Query/Question**
Do the libraries use FabricIO8 (Kubernetes Client): https://github.com/fabric8io/kubernetes-client? Per https://github.com/fabric8io/kubernetes-client#who-uses-kubernetes--openshift-java-client, it says Microsoft Azure Libraries for Java is one of FabricIO8's users, but it seems FabricIO8 is not in any pom files of this repo.

***Why is this not a Bug or a feature Request?***
This question is to confirm whether azure-libraries-for-java depends on FabricIO8.

**Setup (please complete the following information if applicable):**
 - JRE Version: N/A
 - SDK Version: N/A
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [Y] Query Added
- [Y] Setup information Added

**Comment by yungezz** [comment]
I don't think azure-libraries-for-java depends on FabricIO8, add @ChenTanyi to help confirm.

**Comment by ChenTanyi** [comment]
@weiqingy 
For main released package, we don't provide any kubernetes execution. Thus no dependency on `FabricIO8/kubernetes-client`.
For sample package (not released, only for providing samples), we use `FabricIO8/kubernetes-client` to access AKS as an example in https://github.com/Azure/azure-libraries-for-java/blob/28c882956b8774cade9795a4381a5c74f454e913/azure-samples/pom.xml#L163-L167

**Comment by weiqingy** [comment]
Got it. Thanks for confirming, @ChenTanyi @yungezz
