### ISSUE TITLE
Azure VirtualMachine runShellScriptAsync function is not working...

### ISSUE THREAD

**Issue by cjhoon1014** [Azure/azure-libraries-for-java#1400]
**Query/Question**
I'm using Azure JAVA SDK. 
I try to Azure VirtualMacine runShellScriptAsync  function like under this : 

`String subscription = "something...";
String resourceGroupName= "something...";
String vmName= "something...";

VirtualMachine linuxVM = AzureUtils.azureResourceManager.virtualMachines().getById("/subscriptions/"+subscription+"/resourceGroups/"+resourceGroupName+"/providers/Microsoft.Compute/virtualMachines/"+vmName);

List<String> cmdList = new ArrayList<>();
cmdList.add("sudo apt-get update");
cmdList.add("sudo apt-get install $name");

List<RunCommandInputParameter> parameters = new ArrayList<RunCommandInputParameter>();
RunCommandInputParameter arg1 = new RunCommandInputParameter();
arg1.withName("name");
arg1.withValue("git");
parameters.add(arg1);

linuxVM.runShellScriptAsync(cmdList, parameters);`

but this code not working... (but linuxVM.runShellScript() function is working..)
why async function code is not working? 
could you check or let me know solution, please...
(or something sample code please!)

***Why is this not a Bug or a feature Request?***
is only async function not working.

**Setup (please complete the following information if applicable):**
 - JRE Version: JDK 1.8
 - SDK Version: 
 		<dependency>
		    <groupId>com.microsoft.azure</groupId>
		    <artifactId>azure-mgmt-appservice</artifactId>
		    <version>1.41.1</version>
		</dependency>
		<dependency>
		    <groupId>com.microsoft.azure</groupId>
		    <artifactId>azure-client-authentication</artifactId>
		    <version>1.7.12</version>
		</dependency>

 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by weidongxu-microsoft** [comment]
I didn't get it. async method does not work, until you either `await` on it, or call `.Result` to get result.

**Comment by weidongxu-microsoft** [comment]
https://projectreactor.io/

**Comment by cjhoon1014** [comment]
> I didn't get it. async method does not work, until you either `.block` to wait on it, or use e.g. `.flatMap` or `.map` to concat it with other operations.


i was don't know how to use async method. 
okay, i will try this. 

thanks.

**Comment by weidongxu-microsoft** [comment]
@cjhoon1014 
Please note that the new SDK (2.x.x) switch to use Reactor for async.
https://aka.ms/azsdk/java/mgmt

If you only started using the Azure Java management SDK, you might be better start with the new SDK.

**Comment by cjhoon1014** [comment]
@weidongxu-microsoft  thank you so much. i will try this too. Thanks.
