### ISSUE TITLE
SqlDatabase.inner().getTags() isn't populated when loading databases from a SqlServer

### ISSUE THREAD

**Issue by anuj-soni1989** [Azure/azure-libraries-for-java#1425]
Trying to fetch tags from SqlDatabase object, tried the Async methods as well.
`List<SqlDatabase> databasesList = sqlServer.databases().list();

                    List<AzureSQLServerDataStream.SqlDatabase> sqlDatabases = Lists.newArrayList();

                    databasesList.stream().forEach(sqlDatabase -> {
                    sqlDatabase.inner().getTags()

}`
when I do a **SqlDatabase db = sqlDatabase.refresh();** , the **db** object then has the tags, but we can't do this for each SqlDatabase object as we can have 100s of databases, can this be added to the databases.list() or listAsync() call?

Tried this on version 1.31.1 and 1.41.3

**Comment by weidongxu-microsoft** [comment]
@anuj-soni1989

This lib is deprecated. Would you try migrate to https://aka.ms/azsdk/java/mgmt ? It contains a migration guide.

**Comment by anuj-soni1989** [comment]
Thank you! I'll check it out.
