### ISSUE TITLE
NullPointerException when listing metric definitions

### ISSUE THREAD

**Issue by ardias** [Azure/azure-libraries-for-java#161]
Hi,
MetricDefintionsInner is throwing NullPointerException when the resource does not exist.
When I call method `list(resourceUri)` and the resource does not exist then the `body()` of the response is null and there is a call to `items()`, throwing the aforementioned NullPointer:
The line is this one :

https://github.com/Azure/azure-libraries-for-java/blob/eb53b57acb4b7d9bfee8ad01ba4abb5f558b436b/azure-mgmt-monitor/src/main/java/com/microsoft/azure/management/monitor/implementation/MetricDefinitionsInner.java#L121

It seems errors, are not being properly handled, as there is an errorBody that indicates the problem (ex: `{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.ServiceBus/namespaces/whatever' under resource group 'Default-ServiceBus-NorthCentralUS' was not found."}}`)
I'm using the current released version, 1.5.1.

**Comment by hovsepm** [comment]
@ardias please upgrade to 1.6 and let me know if you are still hitting this issue. We regenerated Monitor in that release.

**Comment by ardias** [comment]
@hovsepm thanks, but I cant seem to find version 1.6. Master is still on 1.52-SNAPSHOT form what i can see. Can you point me to the version you're referring to?

**Comment by jianghaolu** [comment]
@ardias Try looking for it on search.maven.org. We are still preparing out announcement blog but you should be able to start using it today!

**Comment by ardias** [comment]
@jianghaolu Thanks. I'll try it out and comment here with the result.

**Comment by ardias** [comment]
Hi @jianghaolu 
I've just tested with version 1.6 and it still fails. The "body()" of the result is still null, so when creating the ServiceReponse with "result.body().items()" it throws the NullPointer. Line 122 on MetricDefinitionsInner.java

Apart from that, the interface is now cleaner and looks a lot better. Kudos!

**Comment by hovsepm** [comment]
@ardias thanks for info. I'll schedule the fix for the nearest release.
