### ISSUE TITLE
How to get AKS access profiles?

### ISSUE THREAD

**Issue by umbrant** [Azure/azure-libraries-for-java#173]
Hi,

I'm trying to get the kubeconfig files for a cluster after it's been created. I can do this on the CLI as follows:

https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_get_credentials

Is there a way of doing this with the Java API? I see some mentions in ManagedClusterInner but it doesn't seem hooked up.

Thanks,
Andrew

**Comment by milismsft** [comment]
Use KubernetesCluster.adminKubeConfigContent() or KubernetesCluster.userKubeConfigContent(); there is recent a service change though that causes the version 1.6 or earlier of the Java SDK to fail getting the expected content. A fix was already pushed in the live repo and it will be there in v1.7 (eta release is March 2018).
For more info on how to use this service take a look at the sample code: https://github.com/Azure/azure-libraries-for-java/blob/master/azure-samples/src/main/java/com/microsoft/azure/management/kubernetescluster/samples/DeployImageFromContainerRegistryToKubernetes.java

**Comment by umbrant** [comment]
Hey milis, is the fix for this present somewhere in the GH repo? I tried using master (1.6.1-SNAPSHOT) but it still doesn't seem to work.

Any hope of getting it ported to master if not?

**Comment by milismsft** [comment]
Yes, it should be part of the https://github.com/Azure/azure-libraries-for-java/pull/153 PR payload.

**Comment by umbrant** [comment]
Thanks for the pointer. I did some more digging and believe I found an issue:

https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/implementation/KubernetesClusterImpl.java#L84

I think this should be setting adminKubeConfigContent instead. Getting the userKubeConfig works fine.

**Comment by milismsft** [comment]
Yes, you are right; and thanks for finding the bug and helping with the fix.
