### ISSUE TITLE
After adding MSI, playback tests run increased from 8 minutes to 25

### ISSUE THREAD

**Issue by lenala** [Azure/azure-libraries-for-java#180]
Because of delays somewhere in the code, after adding MSI module running time for playback tests increased from 8 minutes to 25 minutes.

**Comment by anuchandy** [comment]
Addressed in the PR https://github.com/Azure/azure-libraries-for-java/pull/181

**Comment by anuchandy** [comment]
@lenala PR is merged, hence closing the issue. thanks for reporting!
