### ISSUE TITLE
[Discussion] EventHub Auth Rules: merging withPolicyEnabled and forExistingNamespace

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-libraries-for-java#192]
@hovsepm one issue came into mind here is, if we merge these two then the typing experience would be

```java
  authorizationRules()
        .withSendingEnabledForExistingNamespace(string rgName, string nsName)
     |  .withSendingEnabledForExistingNamespaceId(string id)
     |  .withSendingEnabledForExistingNamespace(Namespace ns)
     |  .withListeningEnabledForExistingNamespace(string rgName, string nsName)
     |  .withListeningEnabledForExistingNamespaceId(string id)
     |  .withListeningEnabledForExistingNamespace(Namespace ns)
     |  .withManageEnabledForExistingNamespace(string rgName, string nsName)
     |  .withManageEnabledForExistingNamespaceId(string id)
     |  .withManageEnabledForExistingNamespace(Namespace ns)
```

i.e. user will see 9 methods after the first dot. With the current approach user will see 3 options after first dot

```java
  authorizationRules()
       .withSendingEnabled()
     | .withListeningEnabled()
     | .withManageEnablede()

```

then after second dot 3 options

```java
  authorizationRules()
        .with[Sending, Listening, Manage]Enabled()
     |  .forExistingNamespace(string rgName, string nsName)
     |  .forExistingNamespaceId(string id)
     |  .fForExistingNamespace(Namespace ns)

```

So it's a trade-off between experience `during typing` vs `after typing`. 

Work item:

if we agree to merge this then -> work item will be
1. Deprecate this usage in service bus and offer new as alternative 
2. Break the beta interface in event-hub

**Comment by anuchandy** [comment]
Ok, had a extensive discussion with @milismsft, @selvasingh. Trying to come up with a general pattern for the structure of child definition. The proposed pattern is:

```java
parents()
    .children()
        .define(<name>)
            .withExistingParent(Parent p) | withExistingParent(string, string..) | withExistingParentId(string id)
            .withChildSpecificProperty1(..)
            .withChildSpecificProperty2(..)
            .create();
```

The `define()` on the child MUST followed by a `ParentRef` stage.  `ParentRef` stage provide ways (explained later) to refer the parent. All the withers for the properties of the child  MUST follow this stage. 

The `ParentRef` MUST expose 3 ways of referencing the parent 

1. Using an instance of parent
2. Using a set of string argument that uniquely identifies the parent
3. Using id of the parent

All three method names MUST follow the pattern - (1) It MUST start with `withExisting`. (2) The next part of the method name MUST be the singular form of the parent collection that is IMMEDIATELY above children accessor. (3) The method that takes id MUST have a last part of the name as `Id`.

For example:

```java
sqlServers()
   .sqlDatabases()
      .define(<db-name>)
         .withExistingSqlServer(SqlServer s) | withExistingSqlServer(string rgname, string servName) | withExistingSqlServerId(string id)
         .withEdition(..)
         .create();
```

```java
eventHubNamespaces()
    .eventHubs()
        .authRules()
           .define(<rule-name>)
           .withExistingEventHub(EventHub s) | withExistingEventHub(string rgname, string nsName, string hubName) | withExistingEventHubId(string id)
           ...
           .create()
```

**Comment by milismsft** [comment]
@anuchandy let's start getting all these guidelines/documentation into a proper place so we know where to look for it; per an early conversation with @selvasingh we should create a new folder "dev-notes" where we can start building a collection of documents we can use as references in future implementation.

**Comment by anuchandy** [comment]
@milismsft definitely, i'm will be doing that once I park v1.7 deliverables. Will copy over the above pattern description to dev-notes.

**Comment by anuchandy** [comment]
initial notes here https://github.com/Azure/azure-libraries-for-java/pull/195, we'll be adding more existing patterns to this md, after adding bunch of patterns we can start thinking of organizing them in better way.

**Comment by anuchandy** [comment]
closing this since the pattern is well documented now (see previous comment).
