### ISSUE TITLE
Creating appsettings/connectionstrings on slots does not work with new configuration

### ISSUE THREAD

**Issue by npeuser** [Azure/azure-libraries-for-java#224]
We are trying to use AppService Deployment slots to enable zero downtime replacements in Azure. As part of this, we are trying to create deployment slots with new configuration, like this:

`DeploymentSlot azureSlot = azure.webApps().getByResourceGroup(RG_NAME, WEBAPP_NAME)
                 .deploymentSlots()
                     .define(SLOT_NAME)
                        .withBrandNewConfiguration()
                        .withJavaVersion(JavaVersion.JAVA_1_8_0_111)
                        .withWebContainer(WebContainer.TOMCAT_8_0_23)
                        .withAppSetting("JAVA_OPTS", getJavaOptions())
                        .withPlatformArchitecture(PlatformArchitecture.X64)
                        .withConnectionString("SQLDB", OUR_CONN_STRING, ConnectionStringType.SQLAZURE)
                        .withWebAppAlwaysOn(false)
                 .create();`

However, this creates a deployment slot without app settings and connection strings. The problem seems to lie here: https://github.com/Azure/azure-libraries-for-java/blob/2f07c26d961dc65f57398f2fc022edcf776f8a87/azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/DeploymentSlotBaseImpl.java#L177-L199

configurationSource is null in the case of a brand new deployment slot. So the actual app settings passed on to the slot are never read because in line 181 it will just emit the object itself, not the app settings.

We have also tried to update the app settings in a subsequent update call, but that didn't work either (we have not spent the time to debug it). I'd also be happy to contribute the fix myself, but I'm still learning what goes where and maybe I am misunderstanding something here :)

Best regards

~ Nils

**Comment by npeuser** [comment]
I've added a PR for this issue with my proposed solution and added tests.
https://github.com/Azure/azure-libraries-for-java/pull/229

**Comment by jianghaolu** [comment]
Closing via #229.
