### ISSUE TITLE
ResourceManagerThrottlingInterceptor synchronization should be scoped to subscription

### ISSUE THREAD

**Issue by milismsft** [Azure/azure-libraries-for-java#231]
Databricks uses the SDK to manage VMs accross hundreds of Azure subscriptions (Databricks customers) from the same java process. We recently ran into an issue where one customer subscription hit the API limit. The ResourceManagerThrottlingInterceptor then started throttling API calls -- the SDK logs show Azure Resource Manager read/write per hour limit reached. Will retry in: 316 seconds.

This sleep should apply only to the specific subscription being throttled. However ResourceManagerThrottlingInterceptor uses a static ReentrantLock for synchronization. This results in all our customer subscriptions being blocked (all SDK calls are blocked) for the duration of the throttling. This means Databricks cannot make any Azure API requests for any of its customers during 5 minutes.

Instead, the lock should be scoped to a single subscription.

**Comment by milismsft** [comment]
@jystephan I can confirm that the throttling applies to all the subscriptions unfortunately. I'll investigate this further and see if we can get a fix for it.

**Comment by jystephan** [comment]
Thanks for the quick answer @milismsft.
