### ISSUE TITLE
ServiceBus entities lack UserMetadata

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-libraries-for-java#3]
_From @SeanFeldman on August 30, 2017 6:17_

`UserMetadata` on all entities ([queues](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queuedescription.usermetadata), [topics](https://docs.microsoft.com/en-ca/dotnet/api/microsoft.servicebus.messaging.topicdescription.usermetadata), and [subscriptions](https://docs.microsoft.com/en-ca/dotnet/api/microsoft.servicebus.messaging.subscriptiondescription.usermetadata)) is missing

_Copied from original issue: Azure/azure-sdk-for-net#3635_

**Comment by anuchandy** [comment]
@jtaubensee (Service Bus PM) could you please comment?

**Comment by jtaubensee** [comment]
@anuchandy - I'm no longer a Service Bus PM, but what @SeanFeldman is talking about, is correct. @ChristianWolf42 should be able to comment further.

**Comment by anuchandy** [comment]
Thanks you @jtaubensee! @ChristianWolf42 could you please take a look?

**Comment by iscai-msft** [comment]
Service Bus supports UserMetadata as seen [here](https://github.com/Azure/azure-service-bus-java/search?q=usermetadata&unscoped_q=usermetadata). Closing this issue now.

**Comment by SeanFeldman** [comment]
@iscai-msft that's inaccurate. Not **all** entities support `UserMetadata`. Rules do not. See https://github.com/Azure/azure-service-bus/issues/209 for details.

**Comment by tudorsibiu90** [comment]
> Service Bus supports UserMetadata as seen [here](https://github.com/Azure/azure-service-bus-java/search?q=usermetadata&unscoped_q=usermetadata). Closing this issue now.

The link is broken. I know for a fact that Subscriptions have userMetadata(a.k.a. Description) but when deploying via ARM, the info does not get through. It's missing. I say reopen this since there are still bugs or you have not covered all of these with your answer.
