### ISSUE TITLE
Recovery services full support

### ISSUE THREAD

**Issue by renutz** [Azure/azure-libraries-for-java#339]
Hi,

When all the APIs from Recovery Services will be finally implemented?

https://docs.microsoft.com/en-us/azure/backup/backup-azure-vms-automation

Thanks

**Comment by yungezz** [comment]
hi @renutz we have below recovery services sdk released, includes resource providers: recoveryservices, recoveryservices.backup and recoveryservices.siterecovery
- https://search.maven.org/search?q=azure-mgmt-recoveryservices

Could you pls check if above package  meet your need? Will close the issue for now, pls create a new issue at https://github.com/Azure/azure-sdk-for-java/issues if any other problem. thanks.
