### ISSUE TITLE
Can `WebApp.warDeploy()` accept `InputStream` as parameter?

### ISSUE THREAD

**Issue by ArchangelSDY** [Azure/azure-libraries-for-java#367]
Hi,

We're integrating war deploy with our Jenkins plugin. However, looks like it only accepts `File` as its parameter[1], which means it must be a real file on local file system. In Jenkins we usually build war files on slaves and read them back as `InputStream` when doing deployment afterwards. Though I can create a temporary file on master machine to work around this, I wonder if it's possible to make it more straightforward by adding another overload to accept `InputStream` as parameter? 

Thanks!

[1]https://github.com/Azure/azure-libraries-for-java/blob/452a6e3f3adb9354c6fedbffa64fb55a60134856/azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/WebApp.java#L41

**Comment by yungezz** [comment]
the linked PR which contains fixing merged already. close the issue for now, feel free to create new issue at https://github.com/Azure/azure-sdk-for-java/issues if met any other problem. thanks.
