### ISSUE TITLE
Support Private DNS Zone Creation

### ISSUE THREAD

**Issue by rturner3** [Azure/azure-libraries-for-java#415]
The SDK does not provide a means to designate DNS Zone to create or update as Public or Private via the "zoneType" parameter available in the Create or Update DNS Zones REST API.

https://docs.microsoft.com/en-us/rest/api/dns/zones/createorupdate#zonetype

**Comment by hovsepm** [comment]
it is shipped with v1.9. Usage sample could be checked [here](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-dns/src/test/java/com/microsoft/azure/management/dns/DnsZoneRecordSetETagTests.java#L121)

**Comment by rturner3** [comment]
Is there any ETA of when v1.9 is planning on being released?

**Comment by hovsepm** [comment]
Shipped today.
