### ISSUE TITLE
Enable service endpoints 

### ISSUE THREAD

**Issue by niteshjain1** [Azure/azure-libraries-for-java#438]
Is there any method to enable service endpoints on a subnet via the sdk.
We can do so via a template, but it is overridden if resource is later updated via the sdk apis

**Comment by milismsft** [comment]
@niteshjain1 Yes, there is; see https://github.com/Azure/azure-libraries-for-java/blob/master/azure-samples/src/main/java/com/microsoft/azure/management/sql/samples/ManageSqlVirtualNetworkRules.java#L64 as an example on how to do that for SQL Virtual Network Rule settings for instance.

**Comment by hovsepm** [comment]
Issue addressed. Closing.
