### ISSUE TITLE
Dependency BOM

### ISSUE THREAD

**Issue by cuizhanming** [Azure/azure-libraries-for-java#464]
Can you support a simple BOM for dependency?
To use one mgmt dependency for example Service Bus, I have to use the root '<artifactId>azure</artifactId>', because of "Azure" root class is there! Then which will import all the others, massive dependencies!

**Comment by dadoonet** [comment]
Thanks @anuchandy for the workaround. This is working well for my use case (compute management).

**Comment by yaohaizh** [comment]
Answered in the issue.
