### ISSUE TITLE
Don't include slf4j-simple as a dependency

### ISSUE THREAD

**Issue by novaterata** [Azure/azure-libraries-for-java#479]
One of your libraries brings in slf4j-simple. Inclusion of any SLF4J implementation prevents integration with any other library that also includes an SLF4J implementation, defeating the purpose of SLF4J.

**Comment by cjemison** [comment]
Can we also not include Jackson as a dependency? Provided scope should be sufficient.

**Comment by mikehearn** [comment]
This is a simple fix - it can just be dropped from the core libraries and imported by samples and tools.
