### ISSUE TITLE
Allow non filtered ActivityLog

### ISSUE THREAD

**Issue by grnadav** [Azure/azure-libraries-for-java#494]
Hello

Currently, when attempting to retrieve ActivityLog via:

`azure.activityLogs().defineQuery().startingFrom(new DateTime(earliest)).endsBefore(new DateTime(latest)).withAllPropertiesInResponse().[PROBLEM]
`

The Filter interface is mandatory (WithActivityLogsSelectFilter), which force me to filter out results, whereas I need all the results (from all resource groups, all resources, all providers).  

Please allow non-filtering flow option.

**Comment by hovsepm** [comment]
@grnadav I'm not sure I understand your request. Filter selection methods are NOT mandatory and you can just call execute after response property selection which should give you what you are looking for. i.e. this code should do the trick
```
azure.activityLogs().defineQuery()
                    .startingFrom(recordDateTime.minusDays(7))
                    .endsBefore(recordDateTime)
                    .withAllPropertiesInResponse()
                    .execute();
```

**Comment by hovsepm** [comment]
Closed as "no repro".
