### ISSUE TITLE
Can't add an existing data disk to a scale set VM

### ISSUE THREAD

**Issue by abrarahmed56** [Azure/azure-libraries-for-java#507]
There's currently no way (that I found at least) of adding a data disk using an existing vhd to an existing scale set vm. It's possible on a regular virtual machine using unmanaged or managed disks using the update() and apply() methods, but on a scale set vm, no such methods seem to exist.

**Comment by yaohaizh** [comment]
@abrarahmed56 https://github.com/Azure/azure-libraries-for-java/commit/37e0ce1cc6d2e7250e71380f02d7fa4c2773b1a6 This issue was recently fixed with the PR in the v1.25.0
