### ISSUE TITLE
sdk coverage for SQL server security audit policy in version 2017-03-01-preview

### ISSUE THREAD

**Issue by vishyr** [Azure/azure-libraries-for-java#528]
Requesting sdk coverage for SQL server security audit policy which is included in version 2017-03-01-preview (https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/serverSecurityAlertPolicies.json)

**Comment by selvasingh** [comment]
See #543 :-)

**Comment by hovsepm** [comment]
closed as duplicate.
