### ISSUE TITLE
please add new region in Region.java

### ISSUE THREAD

**Issue by taroyutao** [Azure/azure-libraries-for-java#531]
China azure has added two regions: china north2 and china east2. please add them in [Region.java](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/Region.java) in next version.

Thanks in advance.

**Comment by taroyutao** [comment]
Any update?

**Comment by taroyutao** [comment]
any update？

**Comment by jianghaolu** [comment]
@taroyutao I'll add to the next release.

**Comment by jianghaolu** [comment]
Duplicate of https://github.com/Azure/azure-libraries-for-java/issues/481, closing via https://github.com/Azure/azure-libraries-for-java/pull/573.
