### ISSUE TITLE
[Documentation] Does this library support IotHUB Management 

### ISSUE THREAD

**Issue by bearrito** [Azure/azure-libraries-for-java#539]
The previous library had IoT support. Was that lost in the move?

**Comment by ChrisBNR** [comment]
Along with above question, api-specs.json IoT Hub should have support but the below listed package does not exist:

"iothub": {
    "dir": "azure-mgmt-devices",
    "source": "specification/iothub/resource-manager/readme.md",
    "package": "com.microsoft.azure.management.devices",
    "args": "--payload-flattening-threshold=1 --tag=package-2017-01"
  },

**Comment by ardias** [comment]
+1

**Comment by bearrito** [comment]
Any follow up from maintainers? This is becoming an issue for us. Should I file a support ticket through the portal?

**Comment by yungezz** [comment]
hi @bearrito here's IoTHub mgmt package source code https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/iothub
maven packages: https://search.maven.org/search?q=azure-mgmt-iothub

Let us know whether this is what you need. Close the issue for now, feel free to create new issue at https://github.com/Azure/azure-sdk-for-java/ if any other question. thanks.
