### ISSUE TITLE
NoSuchElementException when get resources

### ISSUE THREAD

**Issue by gavinfish** [Azure/azure-libraries-for-java#559]
When I use this sdk to get resources like WebApp or DeploymentSlot from azure, it will throw a runtime exception `NoSuchElementException`, why not return a null element or throw a self defined Exception like NoSuchResourceException instead a runtime exception?

**Comment by jianghaolu** [comment]
@gavinfish `NoSuchElementException` is not defined by us. It's thrown by RxJava to indicate that there's an operation trying to access an item in the stream, e.g., `.first()`, `.last()`, `.single()`, etc.
