### ISSUE TITLE
Retrieving all metric dimensions / metadatavalues for a given metric without specifying the dimension in $filter

### ISSUE THREAD

**Issue by akodali18** [Azure/azure-libraries-for-java#561]
My Objective : Retrieve all the metric values (with their dimensions") that are listed in https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-supported-metrics#microsoftstoragestorageaccountsblobservices 

What I tried out:
Use the REST API : https://docs.microsoft.com/en-us/rest/api/monitor/metrics/list to get the list of metrics.
corresponding java sdk call: https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-monitor/src/main/java/com/microsoft/azure/management/monitor/implementation/MetricsInner.java#L71 

Currently, documentation says ( https://docs.microsoft.com/en-us/rest/api/monitor/metrics/list#timeserieselement )
 "metadatavalues" : "the metadata values returned if $filter was specified in the call." -> 
 This means I have to do multiple GET requests like below, to retrieve metrics (with "metadatavalues"):

Ex:
GET "https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/rg1/providers/Microsoft.Storage/storageAccounts/sa1/blobServices/deafult/providers/microsoft.insights/metrics?api-version=2018-01-01&metricnames=BlobCapacity,BlobCount&$filter=BlobType eq ‘*’"
GET "https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/rg1/providers/Microsoft.Storage/storageAccounts/sa1/blobServices/deafult/providers/microsoft.insights/metrics?api-version=2018-01-01&metricnames=Ingress&$filter=BlobType eq ‘*’"

What I want:  Is there a way to retrieve "dimensions" of all the metrics by default with a single call for all the metrics specified in "metricnames" query parameter ?

Note:
I can't mix and match metricnames with metadata values in $filter (as it results in error as below- which makes sense i think):
Ex:
GET "https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/rg1/providers/Microsoft.Storage/storageAccounts/sa1/blobServices/deafult/providers/microsoft.insights/metrics?api-version=2018-01-01&metricnames=BlobCapacity,Ingress&$filter=GeoType eq '*' and BlobType eq '*'

 "message": "Metric: BlobCapacity does not support requested dimension combination: geotype,blobtype, supported ones are: BlobType,Tier"

Thank you,
Anil

**Comment by hovsepm** [comment]
@anirudhcavale could you take a look to the issue? This is not related to Fluent SDK.

**Comment by anirudhcavale** [comment]
@akodali18 thanks for posting, I just have a quick clarifying question: are you looking for which dimensions exist on a particular metric. Or do you want to discover the range of potential values for each dimension?

**Comment by akodali18** [comment]
Its neither. I want to retrieve all the metric values (along with dimensions) of multiple metric names of a resource without having to specify a filter. (so that I can get done with a single API call).

For Ex:  Consider the resource -Microsoft.Storage/storageAccounts/blobServices  (https://goo.gl/ZadG5G )

I want to do a single API/REST call like below:
GET "https://management.azure.com/subscriptions//resourceGroups/rg1/providers/Microsoft.Storage/storageAccounts/sa1/blobServices/deafult/providers/microsoft.insights/metrics?api-version=2018-01-01&metricnames=BlobCapacity,BlobCount,ContainerCount,Transactions,Ingress,Egress

Currently the above call with multiple "metricnames" of the resource will work but Response doesn't contain the dimension values. If i want to get dimension values, I need to break the above call per "metricname" and include query parmeter like "$filter=BlobType eq '*'" . So I need to do many separate calls to azure.

Is there a way by which i can get dimension values included in the response for all "metricnames" without specifying the query parameter "$filter" , so that i could just make a single API call to get what i want.

Thank you,
Anil

**Comment by anirudhcavale** [comment]
Hi Anil,
No it is not possible to make a call for metric (even a single one) and get back all dimensions without using the $filter capability.
You can query for multiple metrics and use the $filter on any dimensions the metrics share. But if you use the $filter and try to filter on dimensions that aren't shared the response will not be what you expect.
#please-close

**Comment by akodali18** [comment]
Thanks for confirming.
