### ISSUE TITLE
Re-add support for API Management

### ISSUE THREAD

**Issue by jwalter** [Azure/azure-libraries-for-java#571]
Support for API Management was introduced in: https://github.com/Azure/azure-libraries-for-java/commit/68df2d7943b733d0aa8f7c843c9d7e8cd3618e1e, but removed again in: https://github.com/Azure/azure-libraries-for-java/commit/e519eda25826516f1dcd4d6e7608940e1988371e and is not included on the roadmap in the README. Is there any chance we will see support for API Management added back any time soon? The commit message for the removal indicates that the Rest API is "non fluent". Does this imply that the Rest API itself needs to be redesigned before the support for it can be re-added?

**Comment by yungezz** [comment]
Hi @jwalter SDK package for API mgmt is still there, but code is moved to another repo.
- source code:  https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/apimanagement/mgmt-v2019_12_01/pom.xml
- maven package https://search.maven.org/artifact/com.microsoft.azure.apimanagement.v2019_12_01/azure-mgmt-apimanagement

will close the issue for now. Feel free to open new issue at https://github.com/Azure/azure-sdk-for-java/issues if any other problem. thanks.
