### ISSUE TITLE
“ADJUST_DATES_TO_CONTEXT_TIME_ZONE” from com.fasterxml.jackson

### ISSUE THREAD

**Issue by rjardines83** [Azure/azure-libraries-for-java#577]
Hello folks.
I just change my code from version 1.2.0 to version 1.15.0 this is my code:

azure.deployments().define(deploymentName)
.withExistingResourceGroup(resourceGroupName)
.withTemplate(templateJson)
.withParameters(parametersJson)
.withMode(DeploymentMode.INCREMENTAL)
.create();

I got the error NoSuchFieldError “ADJUST_DATES_TO_CONTEXT_TIME_ZONE” from com.fasterxml.jackson

Azure sdk 1.15.1
com.fasterxml.jackson 2.7.3

**Comment by jianghaolu** [comment]
Is it possible for you to share the template and parameter JSONs? It would be helpful for us to re-produce the issue.

**Comment by yaohaizh** [comment]
@rjardines83 any update on this issue? Thanks.

**Comment by yungezz** [comment]
hi @rjardines83 we'd like to close the issue for now since no more detail for further investigation. Pls feel free to open new issue at https://github.com/Azure/azure-sdk-for-java/issues if met any error. thanks.
