### ISSUE TITLE
Zip deploy failed for web apps created with region "China-East"

### ISSUE THREAD

**Issue by SummerSun** [Azure/azure-libraries-for-java#586]
Deploy a web app to Azure Web App which was created in Azure China met exception:

![image](https://user-images.githubusercontent.com/5179063/45687856-6afe6680-bb82-11e8-9fb0-9f47df6d58d7.png)

From the investigation, it turns out that the wrong default host name was returned after creation. We could not use `.net` for all web apps.
But the default host name is corrected when we do the deployment again after a while. Thus the deployment could be accomplished successfully too. 
```
@Override
    public String defaultHostName() {
        if (inner().defaultHostName() != null) {
            return inner().defaultHostName();
        } else {
            return "http://" + name() + ".azurewebsites.net";
        }
}

```

**Comment by jianghaolu** [comment]
Fixed as part of https://github.com/Azure/azure-libraries-for-java/pull/651.
