### ISSUE TITLE
Add support for UpdateInstancesAsync and UpdateInstances to IVirtualMachineScaleSets

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-libraries-for-java#6]
_From @hrishi18pathak on June 23, 2017 23:30_

Add support for UpdateInstancesAsync and UpdateInstances to IVirtualMachineScaleSets
just like other calls like ReImage, Reboot etc.
This is useful for doing manual upgrades of VMs in a scaleset (when the policy is set to manual)
Current way of achieving this:
IVirtualMachineScaleSet vmss;
var resp = await vmss.Manager.Inner.VirtualMachineScaleSets.UpdateInstancesAsync

_Copied from original issue: Azure/azure-sdk-for-net#3415_

**Comment by anuchandy** [comment]
already added support for this, will be available as part of v1.4

**Comment by anuchandy** [comment]
Closing this given it is supported now.
