### ISSUE TITLE
VaultImpl copy-paste code issue

### ISSUE THREAD

**Issue by malkochoglu** [Azure/azure-libraries-for-java#601]
In  VaultImpl's populateAccessPolicies() method, while throwing CloudException in if(sp ==null) block, accessPolicy.userPrincipalName() was used. It is for sure null as per code logic. I think  it should be accessPolicy.servicePrincipalName().

**Comment by yaohaizh** [comment]
@xccc-msft, if the issue is true, it will be a real bug we need fix.

**Comment by xccc-msft** [comment]
https://github.com/Azure/azure-libraries-for-java/pull/839
