### ISSUE TITLE
Port traffic manager ATM Multi-value preview feature from C#

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-libraries-for-java#617]
https://github.com/Azure/azure-libraries-for-net/pull/489

**Comment by hovsepm** [comment]
The C# changes are not working at the moment because API version needs to be bumped up to 2018-04.

**Comment by anuchandy** [comment]
[This](https://github.com/Azure/azure-libraries-for-java/blob/807e5008b6f260f1fd598f7b55d5620b3410e43d/azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/management/trafficmanager/TrafficManagerProfile.java#L168) is done in Java, Refer the PR https://github.com/Azure/azure-libraries-for-java/pull/636
