### ISSUE TITLE
Add VM extension fails as additional PATCH request sent and VM purchase plan cannot be updated

### ISSUE THREAD

**Issue by karldmoore** [Azure/azure-libraries-for-java#632]
I followed the sample to add a VM extension but this fails with my set up.  The reason is reported as failure to update purchase plan.  On inspection is appears that a PATCH is sent to update the VM, before the add extension API call.  As the PATCH on the VM fails the VM extension call never gets processed.

If however you call this from the CLI the VM PATCH request is not sent and the extension is successful added.  It appears the PATCH is sent in case something about the VM changed, which in this case it didn't.  But as the backend believes we are trying up update something about the purchase plan the API fails.

The only way I found to work around this is to use reflection to access the ComputeManaged and then use ComputeManager.inner().virtualMachineExtensions() to achieve what I want.

This the REST call that is made, the error received and the body of the request sent.

`Request{method=PATCH, url=https://management.azure.com/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Compute/virtualMachines/XXX=2018-06-01, tags={}}`

` The resource '<id>' of type 'Microsoft.Compute/virtualMachines' does not support updates to the purchase plan.` 

` {
 	"plan": {
 		"name": "hourly",
 		"publisher": "barracudanetworks",
 		"product": "barracuda-ng-firewall"
 	},
 	"properties": {
 		"hardwareProfile": {
 			"vmSize": "Standard_B1ms"
 		},
 		"storageProfile": {
 			"imageReference": {
 				"publisher": "barracudanetworks",
 				"offer": "barracuda-ng-firewall",
 				"sku": "hourly",
 				"version": "7.2.205701"
 			},
 			"osDisk": {
 				"osType": "Linux",
 				"name": "XXX",
 				"caching": "ReadWrite",
 				"createOption": "FromImage",
 				"diskSizeGB": 80,
 				"managedDisk": {
 					"id": "/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Compute/disks/XXX",
 					"storageAccountType": "Standard_LRS"
 				}
 			},
 			"dataDisks": []
 		},
 		"osProfile": {
 			"computerName": "XXX",
 			"adminUsername": "will-be-replaced-by-root",
 			"linuxConfiguration": {
 				"disablePasswordAuthentication": false
 			},
 			"secrets": []
 		},
 		"networkProfile": {
 			"networkInterfaces": [{
 				"id": "/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Network/networkInterfaces/XXX"
 			}]
 		}
 	}
 }`

This is the image that I was trying to add the VM extension to:
https://aws.amazon.com/marketplace/pp/B010GKMEKW?qid=1540380168759&sr=0-2&ref_=srh_res_product_title

This is the guide that I followed:
https://github.com/Azure-Samples/compute-java-manage-virtual-machine-using-vm-extensions/blob/master/src/main/java/com/microsoft/azure/management/compute/samples/ManageVirtualMachineExtension.java

CLI output is show below

`az vm extension set --debug --name OmsAgentForLinux --publisher Microsoft.EnterpriseCloud.Monitoring --resource-group XXX --vm-name XXX --protected-settings '{"workspaceKey":"XXX"}' --settings '{"workspaceId":"XXX"}'`

`https://management.azure.com/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Compute/virtualMachines/XXX/extensions/OmsAgentForLinux?api-version=2018-10-01`

`{
	"location": "ukwest",
	"properties": {
		"publisher": "Microsoft.EnterpriseCloud.Monitoring",
		"type": "OmsAgentForLinux",
		"typeHandlerVersion": "1.7",
		"autoUpgradeMinorVersion": true,
		"settings": {
			"workspaceId": "XXX"
		},
		"protectedSettings": {
			"workspaceKey": "XXX"
		}
	}
}`

**Comment by tsarna** [comment]
This same bug happens when trying to resize a marketplace VM as well, eg doing:

    vm.update().withSize("Standard_B1ms").apply();

It looks like this was broken by commit b1a0cc1dc880d68752500ede0923a418c5e48197, where updateResourceAsync was changed to include the plan in the update even if it hasn't changed.

@karldmoore As a workaround, adding "vm.inner().withPlan(null)" before trying to do the update seems to work. This clears the plan data so the update won't try to send it back.

**Comment by karldmoore** [comment]
Thanks @tsarna, finally got around to looking at this.  Sounds interesting, but can't quite figure out how to work that into the command.  Any ideas?

`virtualMachine.update().defineNewExtension(extension + "Test").withPublisher(publisher).withType(type).withVersion(version)
                        .withMinorVersionAutoUpgrade().withPublicSetting("workspaceId", publicSettingValue)
                        .withProtectedSetting("workspaceKey", protectedSettingValue).attach().apply();`

**Comment by karldmoore** [comment]
Think I answered my own question!  Thanks @tsarna looks like that does the trick.  Thought it had to be declared inline but breaking it up into different statements is fine.

`        virtualMachine.inner().withPlan(null);
        virtualMachine.update().defineNewExtension(extension).withPublisher(publisher).withType(type).withVersion(version)
                        .withMinorVersionAutoUpgrade().withPublicSetting("workspaceId", publicSettingValue)
                        .withProtectedSetting("workspaceKey", protectedSettingValue).attach().apply();`

**Comment by karldmoore** [comment]
Attempting to run this with applyAsync instead of apply also fails.  Haven't got to the bottom of this but will raise another ticket :(

**Comment by ChenTanyi** [comment]
This issue is due to java sdk need to parse all inner into json, but service fails to check the `plan` field.

@mjconnection @Drewm3 Could you please see about it? I think maybe the service blocking the request with same plan is an issue.

Here is a sample json (the response of GET is the same as the request of PUT):
```json
{
    "name": "test",
    "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rgsldkjfle/providers/Microsoft.Compute/virtualMachines/test",
    "type": "Microsoft.Compute/virtualMachines",
    "location": "eastasia",
    "tags": {},
    "plan": {
        "name": "access_server_byol",
        "publisher": "openvpn",
        "product": "openvpnas"
    },
    "properties": {
        "vmId": "4d521521-f0ae-4de1-ba0d-ac322e7a103d",
        "hardwareProfile": {
            "vmSize": "Basic_A0"
        },
        "storageProfile": {
            "imageReference": {
                "publisher": "openvpn",
                "offer": "openvpnas",
                "sku": "access_server_byol",
                "version": "latest"
            },
            "osDisk": {
                "osType": "Linux",
                "name": "test_OsDisk_1_0d51792442d04d80936c06c327e2931b",
                "createOption": "FromImage",
                "caching": "ReadWrite",
                "managedDisk": {
                    "storageAccountType": "Standard_LRS",
                    "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rgsldkjfle/providers/Microsoft.Compute/disks/test_OsDisk_1_0d51792442d04d80936c06c327e2931b"
                },
                "diskSizeGB": 30
            },
            "dataDisks": []
        },
        "osProfile": {
            "computerName": "test",
            "adminUsername": "abc",
            "linuxConfiguration": {
                "disablePasswordAuthentication": false,
                "provisionVMAgent": true
            },
            "secrets": [],
            "allowExtensionOperations": true,
            "requireGuestProvisionSignal": true
        },
        "networkProfile": {
            "networkInterfaces": [
                {
                    "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rgsldkjfle/providers/Microsoft.Network/networkInterfaces/nictest5706386883",
                    "properties": {
                        "primary": true
                    }
                }
            ]
        },
        "provisioningState": "Succeeded"
    }
}
```

**Comment by ChenTanyi** [comment]
> Attempting to run this with applyAsync instead of apply also fails. Haven't got to the bottom of this but will raise another ticket :(

@karldmoore I have tested `applyAsync` successfully. Do you use `applyAsync().wait()`? If so, you need to change it into `applyAsync().toBlocking().last()` like what was written in the inner class.

**Comment by Drewm3** [comment]
I have reached out to the API developers requesting them to take a look at this bug.

**Comment by yaohaizh** [comment]
@Drewm3 any update on this issue?

**Comment by Drewm3** [comment]
In this example is the plan being changed, or is the plan exactly the same as it was when the VM was created? The plan can only be set when the VM is created currently. After the VM is created the PATCH or PUT can include the same plan or it can be null. It just cannot be modified.

The API owner is going to update the API documentation to clarify that the plan can only be set at create time of the VM.

**Comment by ChenTanyi** [comment]
@Drewm3 In the example, the plan is exactly the same as it got from server, which is the same as it was created, but it got error: `The resource '<id>' of type 'Microsoft.Compute/virtualMachines' does not support updates to the purchase plan.`.

**Comment by karldmoore** [comment]
@Drewm3 as @ChenTanyi said, the example doesn't attempt to update anything about the plan (it's just trying to define a new extension).
https://github.com/Azure-Samples/compute-java-manage-virtual-machine-using-vm-extensions/blob/master/src/main/java/com/microsoft/azure/management/compute/samples/ManageVirtualMachineExtension.java#L135

**Comment by Drewm3** [comment]
@ChenTanyi, are you seeing the same error if you attempt to update anything on the VM such as changing the size, or do you only see this error when adding this new extension?

**Comment by ChenTanyi** [comment]
@Drewm3 I'm seeing this error even I didn't change anything. I also see it when changing size.

https://github.com/Azure/azure-libraries-for-java/issues/632#issuecomment-533946925
In my example above, I just sent what I had got from server. It failed with the same error.

This error just happens when the vm uses marketplace image.

**Comment by Drewm3** [comment]
I spoke to the backend team and they believe this error is coming from Azure Resource Manager. 

@vladimirjoanovic, could you please take a look at this.

**Comment by vaibhaw-** [comment]
I have run into this while upgrading azure jars from v1.13.0 to v1.32.1.

One instance of the code creates and attachs a new disk right after a vm create completes. 

```
                vm.update()
                        .defineUnmanagedDataDisk(diskLabel)
                        .withNewVhd(sizeGB)
                         ...
                        .attach()
                        .apply();
```

After upgrade, this is now failing the the aforementioned exception. I suspect that other instances of where we do a vm.update will start failing as well. We do vm.update() to change instances sizes, attach and detach disks.

I tried the workaround mentioned in the conversation above, namely - ` vm.inner().withPlan(null);` and it seems to be solving the issue for now. 

Wanted to know a few things - 
1. Are there any expected side-effects of setting the plan to null when performing operations like attach/detach disks and change size ?
2. Is there fix in progress that is going to be available soon? I would rather wait for a fix if it were coming soon.

Thanks!

**Comment by ChenTanyi** [comment]
@vaibhaw 
1. No, it seems the service treats the `plan` as a constant, so it will not be any side-effects in my observation. Of course, I recommend you use `withPlan(null)` in `try...catch` for fallback.
2. SDK could do nothing about it since the [API](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#plan) does not show the `plan` is not changeable, which means SDK cannot set it as null definitely in every update. If the API have detail about it changeable or not, the SDK could fix it quickly. I' not sure about the service and the ARM side. @Drewm3  @vladimirjoanovic 

cc @yungezz 
Thanks!

**Comment by vaibhaw-** [comment]
@ChenTanyi Thanks for clarifying, I guess I will just do with the null plan. :P

**Comment by tartanapp** [comment]
> This same bug happens when trying to resize a marketplace VM as well, eg doing:
> 
> ```
> vm.update().withSize("Standard_B1ms").apply();
> ```
> 
> It looks like this was broken by commit [b1a0cc1](https://github.com/Azure/azure-libraries-for-java/commit/b1a0cc1dc880d68752500ede0923a418c5e48197), where updateResourceAsync was changed to include the plan in the update even if it hasn't changed.
> 
> @karldmoore As a workaround, adding "vm.inner().withPlan(null)" before trying to do the update seems to work. This clears the plan data so the update won't try to send it back.

Thanks alot, it works very well, but with vm.innerModel().withPlan(null); as Im using AzureResourceManager

**Comment by weidongxu-microsoft** [comment]
next release should be 1.41.2
