### ISSUE TITLE
ResourceGroup：It‘s case-insensitive

### ISSUE THREAD

**Issue by Underwood-M** [Azure/azure-libraries-for-java#652]
When I get the virtualMachine.id() and disk.virtualMachineId(), I find it unequal because ResourceGroup is case-insensitive.
![image](https://user-images.githubusercontent.com/19928099/48524119-fa41a500-e8b9-11e8-9f55-963459637447.png)

**Comment by praries880** [comment]
@Underwood-M  thanks for opening the issue, This is something the compute team needs to investigate. I have labelled the issue such that it will show up on the teams radar.

**Comment by yungezz** [comment]
hi @Underwood-M does above make sense for you? resource group name is case-insensitive. Here's full info from ARM https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules. "Resource names are case-insensitive unless specifically noted in the valid characters column." will close the issue for now. feel free to create new issue at https://github.com/Azure/azure-sdk-for-java if any other asks. thanks.
