### ISSUE TITLE
Unable to get VM ID from scale set VM

### ISSUE THREAD

**Issue by rodrigofraxino** [Azure/azure-libraries-for-java#658]
Unable to get VM ID from scale set VM.

VirtualMachineScaleSetVM#instanceId() method returns the number of the VM inside the scale set (0, 1, 2, etc)

VirtualMachineScaleSetVM#id() returns path of VM (/subscriptions/subscription/resourceGroups/resourceGroupName/providers/virtualMachineScaleSets/scaleSetName/virtualMachines/virtualMachineNumber

There is no function to get the VM ID which is provided through the instance metadata.

**Comment by praries880** [comment]
this is now supported ion the fluent layer : https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetVM.java#L36
