### ISSUE TITLE
Plan to publish the latest version of 'azure-mgmt-datalake-store' on Maven?

### ISSUE THREAD

**Issue by harindersingh861** [Azure/azure-libraries-for-java#66]
Currently, we have very old versions of 'azure-mgmt-datalake-store' on maven. Is there a plan to publish the latest versions there?

**Comment by hovsepm** [comment]
Shipped recently to maven - http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22azure-mgmt-datalake-store%22

**Comment by harindersingh861** [comment]
This shows the latest version is 1.0.0-beta1.4. But we are on 1.6 now. Looks like a very old version got published.

**Comment by ro-joowan** [comment]
@harindersingh861 This is most likely because ADLA and ADLS are not in track with the rest of the libraries yet, as it does not have fluent support.  The plan is to integrate fluent soon.
