### ISSUE TITLE
disablePasswordAuthentication on VM create?

### ISSUE THREAD

**Issue by vincentdo** [Azure/azure-libraries-for-java#674]
Is it possible to do this? It looks like this is an option on the LinuxConfiguration exposed in OSProfile but I can't find a way to configure this property when provisioning a VM using `withLinuxCustomImage`

**Comment by praries880** [comment]
So, according to [this code](https://github.com/Azure/azure-libraries-for-java/blob/5c2b94c60e60fd24955a7f1223a774fdb1760336/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java#L1954) if you leave the adminPassword to be null, the SDK sets the flag to true (same holds for [scalesets](https://github.com/Azure/azure-libraries-for-java/blob/b1a0cc1dc880d68752500ede0923a418c5e48197/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetImpl.java#L1583)).

Does this work for you?
