### ISSUE TITLE
Update ACI to latest Swagger

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-libraries-for-java#676]

**Comment by yungezz** [comment]
latest api version is `2018-10` in ACI after PR https://github.com/Azure/azure-libraries-for-java/pull/744, which is latest stable API version, https://github.com/Azure/azure-rest-api-specs/tree/master/specification/containerinstance/resource-manager/Microsoft.ContainerInstance/stable/2018-10-01. close the issue as fixed now. Pls feel free to create new issue at https://github.com/Azure/azure-sdk-for-java, thanks
