### ISSUE TITLE
Old version of Azure Storage SDK referenced

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-libraries-for-java#685]
Azure management SDK uses an older version of Azure Storage SDK. We are using the latest version of the Storage SDK in our system and causes conflicts when the old version is installed. It'd be great if it can be updated to the latest version.

**Storage SDK info**:

**GroupId**: com.microsoft.com
**ArtifactId**: azure-storage
**Version used by Azure Management SDK**: 6.1.0
**Latest version available**: 8.0.0

**Comment by praries880** [comment]
@jianghaolu Can you look at which specific SDK is using the older version of the storage dataplane and update the issue?

**Comment by jacobw125** [comment]
We ran into this issue and have been reporting on it in the azure-storage-java repo. I have listed the specific SDKs depending on the older version of the storage artifact in that ticket.

https://github.com/Azure/azure-storage-java/issues/400

**Comment by jacobw125** [comment]
Happy to report that the recent update to azure-storage-java (v11.0.0) resolved the namespace issue from my earlier comment.

**Comment by nickzhums** [comment]
@SukruthKS are you still having this issue? If so, please provide more info, thanks

@jacobw125 thanks for your update!

**Comment by amishra-dev** [comment]
Please reactivate if you are still facing and issue
