### ISSUE TITLE
[Feature Req] Create VM with Network Interface name

### ISSUE THREAD

**Issue by Coada** [Azure/azure-libraries-for-java#689]
Hello,

I would like the option of creating a virtual machine with a (new) network interface that has a specific name. If you create a VM `withExistingPrimaryNetwork()` it will create a new network interface that gets attached to the VM, but with an automatic name.

A similar solution already exists for creating a virtual machine with a specific disk name, by calling `withOSDiskName(String name)` that returns a `WithCreate`. I am looking for a similar option, say `withNetworkInterfaceName(String name)`.

**Comment by praries880** [comment]
@Coada can you kindly elaborate on the use case here?

**Comment by Coada** [comment]
Sure @praries880 and @jianghaolu ;

The use case is to create resources with a naming structure. In this particular case I want the Network Interface (and the Disk) to have a name associated to the Virtual Machine so me and my team easier can get an overview of all the resources in the resource group.

Without this feature the Network Interface would be given an autogenerated name and we would not be able to see to what virtual machine it was created to (without having to see the details of it).

**Comment by praries880** [comment]
@Coada Thanks for the response.

**Comment by praries880** [comment]
@Coada 
You should be able to use : 
https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java#L596 to do what you want to achieve.
