### ISSUE TITLE
Upgrade msi module to new stable API version

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-libraries-for-java#693]

**Comment by praries880** [comment]
The work in nutshell is:
 
1.	We need to regenerate
2.	Remove beta annotations
3.	Enable any new APIs
4.	If anything new, then see VM & VMSS MSI flow needs to be updated
5.	Rerun tests, sample and re-record.

Steps:
 (1). we need to start by updating the api-sepc.json file to refer the latest api-version, then regenerate based on that.
(2). Fix any compilation issues that prop up after step1.
