### ISSUE TITLE
Add API to get SQL Database by ID w/o getting SQL Server first.

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-libraries-for-java#7]
_From @olegburov on June 23, 2017 21:24_

In Azure portal, I can get an ID of my SQL Database, which looks like below:

- `/subscriptions/{my-subscription-id-here}/resourceGroups/{My-Resource-Group-here}/providers/Microsoft.Sql/servers/{my-sql-server-here}/databases/{my-sql-database-here}`

Using [Azure Management Libraries for .NET](https://www.nuget.org/packages/Microsoft.Azure.Management.Fluent/) (aka Fluent API) I want to get my Azure SQL Database directly by its ID without getting Azure SQL Server first. Just like I can by using [REST API](https://docs.microsoft.com/en-us/rest/api/resources/resources#Resources_GetById).

```c#
  var credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal(clientId, clientSecret, tenantId, AzureEnvironment.AzureGlobalCloud);
        
  var azure = Azure
    .Configure()
    .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
    .Authenticate(credentials)
    .WithSubscription(subscriptionId);

  var database = azure.SqlServers.Databases.GetById("Sql-Database-Id-Here");
```

If the above solution doesn't look good, then maybe you can extend the `IDatabases` interface with `GetById` method:

```c#
  var sqlServer = azure.SqlServers.GetById("Sql-Server-Id-Here");
  var database = sqlServer.Databases.GetById("Sql-Database-Id-Here");
```

_Copied from original issue: Azure/azure-sdk-for-net#3412_

**Comment by milismsft** [comment]
https://github.com/Azure/azure-libraries-for-java/pull/196 adresses this issue/request.
