### ISSUE TITLE
[FEATURE REQ] Update customData in ScaleSet

### ISSUE THREAD

**Issue by romantsukerman** [Azure/azure-libraries-for-java#709]
**Is your feature request related to a problem? Please describe.**
Currently the customData of a VMSS is not updatable in the SDK. This issue prevents from creating new VMs in the scale set when there is a need to update the customData.

**Describe the solution you'd like**
I would like you to add support in updating customData in the SDK.

**Describe alternatives you've considered**
The only alternative is to create a new scale set instead of the old one, which is a wasteful solution, especially when the customData is the only field that should be updated.

**Additional context**
None

**Information Checklist**
- [X] Description Added
- [X] Expected solution specified

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by romantsukerman** [comment]
Is there any updating regarding the request?

**Comment by praries880** [comment]
@romantsukerman  As of now the rest api spec does not support this. This is a request for the service team.

**Comment by yaohaizh** [comment]
Reopen it since the lib team should add the API to expose the values.

**Comment by weidongxu-microsoft** [comment]
Scheduled in 1.26

```
Sample code:
            vmScaleSet.update()
                    .withCustomData(Base64.encodeBase64String(
                            ("#cloud-config\n" +
                            "packages:\n" +
                            " - apache2").getBytes()))
                    .apply();
```
