### ISSUE TITLE
Internal Server Error is back

### ISSUE THREAD

**Issue by sgireddy** [Azure/azure-libraries-for-java#72]
I cloned this sdk and tweaked to include ConsumtionManager in order to access usage details but ended up getting "Internal Server Error". I had this error before as reported here [https://github.com/Azure/azure-sdk-for-java/issues/1975](https://github.com/Azure/azure-sdk-for-java/issues/1975). The issue is back, given the major changes I am expecting it is related to api-version or the new addition of authorization library (?) Also it seems ConsumptionManager (and others) is no longer going to be a beta from v.1.4.0 but still not included as an object within azure, is there a reason for that?

Here is my stack trace:

    [pool-1-thread-1] INFO com.microsoft.aad.adal4j.AuthenticationAuthority - [Correlation ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Instance discovery was successful
    [main] INFO com.microsoft.azure.management.resources.Resources list - --> GET https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resources?api-version=2016-09-01
    [main] INFO com.microsoft.azure.management.resources.Resources list - Accept-Encoding: gzip
    [main] INFO com.microsoft.azure.management.resources.Resources list - accept-language: en-US
    [main] INFO com.microsoft.azure.management.resources.Resources list - Authorization: Bearer xxxxxxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.resources.Resources list - Connection: Keep-Alive
    [main] INFO com.microsoft.azure.management.resources.Resources list - Content-Type: application/json; charset=utf-8
    [main] INFO com.microsoft.azure.management.resources.Resources list - Host: management.azure.com
    [main] INFO com.microsoft.azure.management.resources.Resources list - User-Agent: Azure-SDK-For-Java/1.3.1-SNAPSHOT OS:Mac OS X/10.13.1 MacAddressHash:2538989e3490e255aeb6e2c23b2d833778d077befc5262b23134c7f4db35c235 Java:1.8.0_131 (ResourceManagementClient, 2016-09-01)
    [main] INFO com.microsoft.azure.management.resources.Resources list - x-ms-client-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.resources.Resources list - <-- 200 OK https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resources?api-version=2016-09-01 (723 ms, 7604-byte body)
    [main] INFO com.microsoft.azure.management.resources.Resources list - Cache-Control: no-cache
    [main] INFO com.microsoft.azure.management.resources.Resources list - Content-Encoding: gzip
    [main] INFO com.microsoft.azure.management.resources.Resources list - Content-Length: 7604
    [main] INFO com.microsoft.azure.management.resources.Resources list - Content-Type: application/json; charset=utf-8
    [main] INFO com.microsoft.azure.management.resources.Resources list - Date: Tue, 28 Nov 2017 18:40:41 GMT
    [main] INFO com.microsoft.azure.management.resources.Resources list - Expires: -1
    [main] INFO com.microsoft.azure.management.resources.Resources list - Pragma: no-cache
    [main] INFO com.microsoft.azure.management.resources.Resources list - Strict-Transport-Security: max-age=31536000; includeSubDomains
    [main] INFO com.microsoft.azure.management.resources.Resources list - Vary: Accept-Encoding
    [main] INFO com.microsoft.azure.management.resources.Resources list - x-ms-correlation-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.resources.Resources list - x-ms-ratelimit-remaining-subscription-reads: 14993
    [main] INFO com.microsoft.azure.management.resources.Resources list - x-ms-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.resources.Resources list - x-ms-routing-request-id: WESTUS2:20171128T184042Z:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - --> GET https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&$filter=usageEnd%20gt%202017-11-01%20and%20usageEnd%20lt%202017-12-01&api-version=2017-04-24-preview
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Accept-Encoding: gzip
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - accept-language: en-US
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Authorization: Bearer xxxxxxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Connection: Keep-Alive
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Content-Type: application/json; charset=utf-8
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Host: management.azure.com
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - User-Agent: Azure-SDK-For-Java/1.3.1-beta-SNAPSHOT OS:Mac OS X/10.13.1 MacAddressHash:2538989e3490e255aeb6e2c23b2d833778d077befc5262b23134c7f4db35c235 Java:1.8.0_131 (ConsumptionManagementClient, 2017-04-24-preview)
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-client-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - <-- 500 Internal Server Error https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&$filter=usageEnd%20gt%202017-11-01%20and%20usageEnd%20lt%202017-12-01&api-version=2017-04-24-preview (10170 ms, 403-byte body)
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Cache-Control: no-cache
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Connection: close
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Content-Length: 403
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Content-Type: application/json; charset=utf-8
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Date: Tue, 28 Nov 2017 18:40:54 GMT
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Expires: -1
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Pragma: no-cache
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Server: Microsoft-IIS/8.5
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Strict-Transport-Security: max-age=31536000; includeSubDomains
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - X-AspNet-Version: 4.0.30319
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-content-type-options: nosniff
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-correlation-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-failure-cause: service
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-ratelimit-remaining-subscription-reads: 14992
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-routing-request-id: WESTUS2:20171128T184055Z:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - X-Powered-By: ASP.NET
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - --> GET https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&$filter=usageEnd%20gt%202017-11-01%20and%20usageEnd%20lt%202017-12-01&api-version=2017-04-24-preview
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Accept-Encoding: gzip
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - accept-language: en-US
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Authorization: Bearer xxxxxxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Connection: Keep-Alive
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Content-Type: application/json; charset=utf-8
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Host: management.azure.com
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - User-Agent: Azure-SDK-For-Java/1.3.1-beta-SNAPSHOT OS:Mac OS X/10.13.1 MacAddressHash:2538989e3490e255aeb6e2c23b2d833778d077befc5262b23134c7f4db35c235 Java:1.8.0_131 (ConsumptionManagementClient, 2017-04-24-preview)
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-client-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - <-- 500 Internal Server Error https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&$filter=usageEnd%20gt%202017-11-01%20and%20usageEnd%20lt%202017-12-01&api-version=2017-04-24-preview (3075 ms, 403-byte body)
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Cache-Control: no-cache
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Connection: close
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Content-Length: 403
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Content-Type: application/json; charset=utf-8
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Date: Tue, 28 Nov 2017 18:40:57 GMT
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Expires: -1
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Pragma: no-cache
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Server: Microsoft-IIS/8.5
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Strict-Transport-Security: max-age=31536000; includeSubDomains
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - X-AspNet-Version: 4.0.30319
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-content-type-options: nosniff
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-correlation-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-failure-cause: service
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-ratelimit-remaining-subscription-reads: 14995
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-routing-request-id: WESTUS2:20171128T184058Z:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - X-Powered-By: ASP.NET
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - --> GET https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&$filter=usageEnd%20gt%202017-11-01%20and%20usageEnd%20lt%202017-12-01&api-version=2017-04-24-preview
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Accept-Encoding: gzip
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - accept-language: en-US
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Authorization: Bearer xxxxxxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Connection: Keep-Alive
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Content-Type: application/json; charset=utf-8
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Host: management.azure.com
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - User-Agent: Azure-SDK-For-Java/1.3.1-beta-SNAPSHOT OS:Mac OS X/10.13.1 MacAddressHash:2538989e3490e255aeb6e2c23b2d833778d077befc5262b23134c7f4db35c235 Java:1.8.0_131 (ConsumptionManagementClient, 2017-04-24-preview)
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-client-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - <-- 500 Internal Server Error https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&$filter=usageEnd%20gt%202017-11-01%20and%20usageEnd%20lt%202017-12-01&api-version=2017-04-24-preview (5905 ms, 403-byte body)
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Cache-Control: no-cache
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Connection: close
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Content-Length: 403
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Content-Type: application/json; charset=utf-8
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Date: Tue, 28 Nov 2017 18:41:03 GMT
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Expires: -1
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Pragma: no-cache
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Server: Microsoft-IIS/8.5
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Strict-Transport-Security: max-age=31536000; includeSubDomains
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - X-AspNet-Version: 4.0.30319
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-content-type-options: nosniff
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-correlation-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-failure-cause: service
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-ratelimit-remaining-subscription-reads: 14997
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-routing-request-id: WESTUS2:20171128T184104Z:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - X-Powered-By: ASP.NET
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - --> GET https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&$filter=usageEnd%20gt%202017-11-01%20and%20usageEnd%20lt%202017-12-01&api-version=2017-04-24-preview
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Accept-Encoding: gzip
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - accept-language: en-US
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Authorization: Bearer xxxxxxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Connection: Keep-Alive
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Content-Type: application/json; charset=utf-8
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Host: management.azure.com
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - User-Agent: Azure-SDK-For-Java/1.3.1-beta-SNAPSHOT OS:Mac OS X/10.13.1 MacAddressHash:2538989e3490e255aeb6e2c23b2d833778d077befc5262b23134c7f4db35c235 Java:1.8.0_131 (ConsumptionManagementClient, 2017-04-24-preview)
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-client-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - <-- 500 Internal Server Error https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&$filter=usageEnd%20gt%202017-11-01%20and%20usageEnd%20lt%202017-12-01&api-version=2017-04-24-preview (2766 ms, 403-byte body)
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Cache-Control: no-cache
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Connection: close
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Content-Length: 403
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Content-Type: application/json; charset=utf-8
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Date: Tue, 28 Nov 2017 18:41:07 GMT
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Expires: -1
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Pragma: no-cache
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Server: Microsoft-IIS/8.5
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - Strict-Transport-Security: max-age=31536000; includeSubDomains
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - X-AspNet-Version: 4.0.30319
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-content-type-options: nosniff
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-correlation-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-failure-cause: service
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-ratelimit-remaining-subscription-reads: 14997
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - x-ms-routing-request-id: WESTUS2:20171128T184107Z:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    [main] INFO com.microsoft.azure.management.consumption.UsageDetails list - X-Powered-By: ASP.NET
    com.microsoft.azure.management.consumption.ErrorResponseException: Status code 500, {"error":{"code":"InternalServerError","target":"https://billing.windowsazure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&$filter=usageEnd%20gt%202017-11-01%20and%20usageEnd%20lt%202017-12-01&api-version=2017-04-24-preview","message":"The server encountered an internal error. Please retry the request."}}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    Status code 500, {"error":{"code":"InternalServerError","target":"https://billing.windowsazure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&$filter=usageEnd%20gt%202017-11-01%20and%20usageEnd%20lt%202017-12-01&api-version=2017-04-24-preview","message":"The server encountered an internal error. Please retry the request."}}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
        at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
        at com.microsoft.azure.management.consumption.implementation.UsageDetailsInner.listDelegate(UsageDetailsInner.java:307)
        at com.microsoft.azure.management.consumption.implementation.UsageDetailsInner.access$000(UsageDetailsInner.java:37)
        at com.microsoft.azure.management.consumption.implementation.UsageDetailsInner$10.call(UsageDetailsInner.java:294)
        at com.microsoft.azure.management.consumption.implementation.UsageDetailsInner$10.call(UsageDetailsInner.java:290)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
        at rx.Observable.unsafeSubscribe(Observable.java:10144)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10240)
        at rx.Observable.subscribe(Observable.java:10207)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
        at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
        at com.microsoft.azure.management.consumption.implementation.UsageDetailsInner.list(UsageDetailsInner.java:192)
        at com.bpcs.azure.util.AzSDK$.consumptionDetails(AzSDK.scala:38)
        at com.bpcs.azure.resources.ManageResources$.delayedEndpoint$com$bpcs$azure$resources$ManageResources$1(ManageResources.scala:27)
        at com.bpcs.azure.resources.ManageResources$delayedInit$body.apply(ManageResources.scala:17)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.bpcs.azure.resources.ManageResources$.main(ManageResources.scala:17)
        at com.bpcs.azure.resources.ManageResources.main(ManageResources.scala)
    Disconnected from the target VM, address: '127.0.0.1:59641', transport: 'socket'

**Comment by anuchandy** [comment]
@muazmian [From consumption service team], Muaz could you please take a look?

**Comment by sgireddy** [comment]
@muazmian @anuchandy Any update on this?

**Comment by sgireddy** [comment]
@muazmian @anuchandy Is there a public JIRA or TFS task board where we could track releases, upcoming changes and submit change requests etc?

**Comment by muazmian** [comment]
Hi @sgireddy 

Unfortunately, This is a preview API and it has some known issues.

Alternatively, can you look at Microsoft.Commerce or newer version of Microsoft.Consumption?

**Comment by sgireddy** [comment]
Yes, I am using a customized version of this library, I need the latest api-version of Microsoft.Consumption. Could you please provide details?

**Comment by sgireddy** [comment]
@muazmian
I got this when I tried with an invalid api-version: "The supported api-versions are '2017-04-24-preview,2017-06-30-preview,2017-11-30"

Looks like 2017-04-24-preview is still the best version for me as the others didn't even recognize my subscription. Looks like this issue is related to [Azure/azure-sdk-for-java#1975](https://github.com/Azure/azure-sdk-for-java/issues/1975). could you take a look?


2017-04-24-preview
"message": "The server encountered an internal error. Please retry the request."

2017-06-30-preview
 "message": "No subscriptions were found for guids 

2017-11-30
"message": "No subscriptions were found for guids

**Comment by sgireddy** [comment]
@muazmian @anuchandy 

Microsoft.Consumption has been under preview since April, your own api-version says its NOT preview anymore and yet you are no where to help! 

Asking somebody to give up just because you can't fix an issue is perhaps the most cowardice act for any conscious developer. I wish you guys show some empathy towards fellow professionals. I wasted weeks of my precious time. 

@microsoft SUCKS.

**Comment by anuchandy** [comment]
@sgireddy, I had a chat with @muazmian and others owning the service. The usage data provided by the `preview` version of consumption service is not that useful and service team is deprecating the `preview` version in favor of stable version. The new version of service is being deployed and should be functional by mid of Dec 2017. We have updated version of sdk client which is based on this stable [api version](https://github.com/Azure/azure-libraries-for-java/blob/ce2f9196179f6e4773150e5eba31f022a87d86c5/azure-mgmt-consumption/src/main/java/com/microsoft/azure/management/consumption/implementation/ConsumptionManagementClientImpl.java#L192). At this point, the best alternative is to wait for service to be deployed instead of relying on preview + deprecating api version. I will ping you once the new service is ready to use.

**Comment by sgireddy** [comment]
@anuchandy Seems the latest release fixed this issue. Thank You.
