### ISSUE TITLE
NPE when comparing VM powerstate in ExpandableStringEnum.equals()

### ISSUE THREAD

**Issue by ashbondu** [Azure/azure-libraries-for-java#721]
When comparing the powerstate, seeing NPE in ExpandableStringEnum.equals(). 

Syntax used is PowerState.RUNNING.equals(vm.powerState()) 
Note: The powerstate returned from Azure was null due to an intermediate error.

Stacktrace:
java.lang.NullPointerException: null
at com.microsoft.azure.management.resources.fluentcore.arm.ExpandableStringEnum.equals(ExpandableStringEnum.java:93) ~[vmw-azure-mgmt-resources-1.17.0.jar:1.17.0]

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by yaohaizh** [comment]
Fixed on PR#737.
