### ISSUE TITLE
[FEATURE REQ] Please provide getAll method for app service attributes like RuntimeStack

### ISSUE THREAD

**Issue by Flanker32** [Azure/azure-libraries-for-java#748]
**Is your feature request related to a problem? Please describe.**
I'm working on the maven plugin for azure app service and azure functions, we need to get attributes from users' configuration. Some attributes like `RuntimeStack` didn't provide a `fromString` method, or some attributes like `PricingTier` their `fromString` method didn't fit our requirement, so I need a `getAll` method to get all available attributes to compare with user's input and get the result,

**Describe the solution you'd like**
Make these attributes to enum or provide a get all method

**Describe alternatives you've considered**
For now i need to hard code all possible values or use reflect to get available values.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by nickzhums** [comment]
After deeper look, this seems to be a Mgmt issue. Removed service attention label to avoid confusion, sorry

**Comment by weidongxu-microsoft** [comment]
I will do RuntimeStack and PricingTier.

This is manual work, so please let me know if you want any more enum.

**Comment by weidongxu-microsoft** [comment]
OK, it is still `getAll()`
