### ISSUE TITLE
[BUG] Cannot retrieve SQL tags from SDK.

### ISSUE THREAD

**Issue by metaldectr** [Azure/azure-libraries-for-java#752]
**Describe the bug**
Cannot retrieve tags from SDK for SQL Database. But I can see tags using CLI.

**To Reproduce**

1. Create SQL Database
2. Assign tags for this db.
3. Check that using _`az sql db list --ids /subscriptions/**subscrId**/resourceGroups/**resourseGroupName**/providers/Microsoft.Sql/servers/**server-name**/databases/**db-name**`
see that `tags{}` is not empty.

Using SDK call `authenticated.withSubscription(subscriptionId).sqlServers().list().get(0).databases().list().get(0).inner().getTags()` return null.

**Setup (please complete the following information):**
 - Mac OS
 - IDE :  IntelliJ
 - Version of the Library : 1.19.0

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by jaredmoo** [comment]
This is known issue with the 2014 api-version. It is fixed in all later api-versions such as 2017-03-preview or 2017-10-preview. @metaldectr which namespace are you using for listing databases?

**Comment by yaohaizh** [comment]
@weidongxu-microsoft , we have updated the SQL version. Please help verify this issue. Thanks.

**Comment by krjackso** [comment]
I'm also running into this issue with SqlDatabase and SqlElasticPool.  It seems to me like they should both implement [Resource](https://azure.github.io/azure-libraries-for-java/com/microsoft/azure/management/resources/fluentcore/arm/models/Resource.html) similar to how the [SqlServer](https://azure.github.io/azure-libraries-for-java/com/microsoft/azure/management/sql/SqlServer.html) class does.

**Comment by yaohaizh** [comment]
This need update SQL spec to composite v3, which is required lots of update.

**Comment by yaohaizh** [comment]
@ChenTanyi please see whether composite V1 has the fix for tagging issue.

**Comment by ChenTanyi** [comment]
@yaohaizh @metaldectr The service have fixed this issue for the composite V1 (databases api-version 2014-04-01, current SDK version)

**Comment by ChenTanyi** [comment]
@metaldectr we have verified that this issue was solved. If you still meet the problem, feel free to re-open it again. Thanks!
