### ISSUE TITLE
[Intermittent] Tagging snapshot using generic approach fails

### ISSUE THREAD

**Issue by NikolicMarko** [Azure/azure-libraries-for-java#756]
**Describe the bug**

Snapshot is created using Java SDK 1.22. Immediately after creation I tried to tag resource using following code 
   client.genericResources() .getById(resourceId) .update() .withTag(key, value) .apply();
Exception occurred (see below)

I was able to do this with SDK version 1.12.
This issue is intermittent. It got resolved after couple of hours without any action on my side. I don't know if someone enabled IncrementalSnapshots feature or did something else.

While I was experiencing described issue I was able to tag different resources (virutal machines and disks) using generic way. 

I was able to tag snapshot using relevant class instead generic way
client.snapshots() .getById(resourceId) .update() .withTag(key, value) .apply();

***Exception or Stack Trace***
com.microsoft.azure.CloudException: This subscription is not registered to use Microsoft.Compute/IncrementalSnapshots feature

**To Reproduce**
* Create snapshot using Java SDK
* try to tag newly created snapshot with following code
  client.genericResources() .getById(resourceId) .update() .withTag(key, value) .apply();

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: Mac OS Mojave 10.14.5
 - IDE : Eclipse 2018-09
 - Version of the Library used: Azure Java SDK 1.22

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by yaohaizh** [comment]
@NikolicMarko, I used this example to create an snapshot: https://github.com/Azure-Samples/managed-disk-java-create-virtual-machine-using-specialized-disk-from-snapshot

Then, at  line of 121, I added the following code snippets and everything went well. So could you help share your code snippet for investigation?  Thanks. 

```java CreateVirtualMachineUsingSpecializedDiskFromSnapshot.java: Line121
                       
Snapshot osSnapshot = azure.snapshots().define(managedOSSnapshotName)
                    .withRegion(region)
                    .withExistingResourceGroup(rgName)
                    .withLinuxFromDisk(osDisk)
                    .create();

            System.out.println("Created managed snapshot holding OS: " + osSnapshot.id());

            azure.genericResources().getById(osSnapshot.id()).update().withTag("testing", "testingTag").apply();
            System.out.println(osSnapshot);
            // // Utils.print(osSnapshot); TODO
```

**Comment by NikolicMarko** [comment]
The only difference is that I've created snapshot of data disk so code looks like this

`Snapshot osSnapshot = azure.snapshots().define(managedOSSnapshotName)
                    .withRegion(region)
                    .withExistingResourceGroup(rgName)
                    .withDataFromDisk(dataDisk)
                    .create();`

I can't reproduce it right now. I've experienced this issue for couple of hours, then it got fixed without any actions on my side.

**Comment by yaohaizh** [comment]
@NikolicMarko then it is hard for us to diagnostic this situation. @praries880 , do we have any logging for diagnostic this one-time situation?

**Comment by nickzhums** [comment]
Hi @NikolicMarko , are you still experiencing this issue? Let us know, thanks!

**Comment by snaheth** [comment]
Closing the issue given no response to the last 2 tagged questions. Please reopen if you're still experiencing this.
