### ISSUE TITLE
[FEATURE REQ] update Eventhub to use the latest swagger specs

### ISSUE THREAD

**Issue by praries880** [Azure/azure-libraries-for-java#757]
Even though the latest API version is still https://github.com/Azure/azure-rest-api-specs/tree/master/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2017-04-01, it has some changes in it form the last time we updated EventHub.

We need tp update eventhub to use tle latest rest specs.

**Comment by yaohaizh** [comment]
Updated the API.
