### ISSUE TITLE
[BUG] In azure-mgmt-appservice , getting minTLSVersion as None Always

### ISSUE THREAD

**Issue by arun542** [Azure/azure-libraries-for-java#764]
I am using the version 1.21.0, using listFunctions method to list all functions. For each function tried using -> func.inner().siteConfig().minTlsVersion() to get the TLS version. Getting null always. Not sure

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by nickzhums** [comment]
@weidongxu-microsoft Could you please take a look a this, thanks

**Comment by weidongxu-microsoft** [comment]
@arun542 
Please use `func.minTlsVersion()` in 1.29

**Comment by yaohaizh** [comment]
Close as the issue had been fixed in 1.29

**Comment by weidongxu-microsoft** [comment]
In any case if you still see null, you can do func.refresh() before checking siteConfig.
