### ISSUE TITLE
Expose withers to specify certs for VMSS

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-libraries-for-java#771]
**Is your feature request related to a problem? Please describe.**
Customers are unable to specify cert for VMSS.

**Describe the solution you'd like**
Recommendation is to expose withers in the optional stage of VMSS definition and update for adding and removing certs.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Description Added
- [X ] Expected solution specified

**Comment by yaohaizh** [comment]
Close as it has been added.
