### ISSUE TITLE
[FEATURE REQ] resource management - DeploymentOperationProperties - missing 'provisioningOperation' attribute?

### ISSUE THREAD

**Issue by vihanp** [Azure/azure-libraries-for-java#772]
I want to get provisioning operation (type) from deployment operation detail.
Azure portal shows the provisioning operation (Create, Action, Read etc.) in each operation detail.
This information is also availabile in REST response (via GET https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/deployments/{deploymentName}/operations/{operationId}?api-version=2019-05-01
).
However the provisioningOperation property is not exposed in java sdk class DeploymentOperationProperties.

**Is your feature request related to a problem? Please describe.**
In a client application, I need to deploy a resource template to an existing resource group. In order to distinguish resources created by that deployment from other resources in group I want to tag them with specific tag (order id). 
My solution is to traverse deployment operations, pick those that are CREATE operations, and apply tag to Target Resource for each of them that are finished.
I want to ignore operations that do not create resource rather that read or action upon resources.
Therefore I want to know the provisioningOperation (Create, Action...) property for each of deployment operation.

**Describe the solution you'd like**
To have this property available in java class.

**Describe alternatives you've considered**
I use REST nowadays but I would rather like to use java resource management SDK.

**Comment by maggiepint** [comment]
Hi, thanks for sending us this feedback. We have routed this to the appropriate team for follow-up.

**Comment by yaohaizh** [comment]
This is not exposed by the REST API specification: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-05-10 though it can be found on the REST response. Please file an issue on the rest spec repo for specification.

**Comment by dennis-benzinger-hybris** [comment]
The REST documentation knows this field now (currently at API level 2019-10-01):
https://docs.microsoft.com/en-us/rest/api/resources/deploymentoperations/get#provisioningoperation

**Comment by weidongxu-microsoft** [comment]
Currently we are still on 2019-08-01
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-08-01/resources.json

**Comment by xccc-msft** [comment]
@vihanp @dennis-benzinger-hybris Please check the [PR](https://github.com/Azure/azure-libraries-for-java/pull/1243) adding provisioningOperation. We will plan to release this week.

**Comment by xccc-msft** [comment]
Close this as released in 1.36.0.
