### ISSUE TITLE
[BUG] - In Azure Storage File Services, CAPACITY specific metrics are updating with a delay more than a PT1H interval

### ISSUE THREAD

**Issue by gangadharaswamy** [Azure/azure-libraries-for-java#777]
**Description**
In Azure Storage File Service, CAPACITY specific metrics like `FileCapacity`, `FileCount`, `FileShareCount`, etc are reporting actual values with a delay more than a PT1H collection interval, both on azure metrics monitor and via REST API call.
Here it took 4 collection intervals to reflect the actual metric values(_screenshots attached_).

**To Reproduce**
Create a storage account, create a file share & upload files. Wait for one PT1H interval and observe the values on metrics monitor. Also check the REST API call response. CAPACITY specific metrics (file capacity, file count, etc) take more than one PT1H to reflect the actual value.

**Expected behavior**
Capacity specific metrics have collection interval of PT1H, expected to see actual metric values on the next immediate collection cycle.

**Screenshots**
_File upload time_:
![image](https://user-images.githubusercontent.com/13899362/60817816-04524400-a1ba-11e9-8027-6a8b037ae54c.png)

_Metrics Monitor_:
![image](https://user-images.githubusercontent.com/13899362/60817866-2055e580-a1ba-11e9-8d48-9688adea30a4.png)

**Setup (please complete the following information):**
 - OS: NA
 - IDE : NA

**Comment by jeffpatt24** [comment]
For Azure Files capacity metrics, the values are refreshed every two hours.

**Comment by jeffpatt24** [comment]
The Azure Metrics doc states the values are refreshed daily but it's actually every two hours: https://docs.microsoft.com/en-us/azure/storage/common/storage-metrics-in-azure-monitor#capacity-metrics

**Comment by jeffpatt24** [comment]
#please-close
