### ISSUE TITLE
[QUERY] should azure endpoint (Azure) be cached?

### ISSUE THREAD

**Issue by vihanp** [Azure/azure-libraries-for-java#789]
**Query/Question**
In my service that is managing Azure resources on behalf of it's user, I'm obtaining azure endpoint like this:

```
Azure azure = Azure.configure()
                .withLogLevel(logLevel)
                .authenticate(credentials)
                .withSubscription(subscriptionId);
```
We estimate to have like 100 accounts with different creds/subscription id.

Can/should this Azure instance be cached in between calls  and what's correct cache evict strategy (how long should one authenticated Azure client be cached)? I assume it is safe to share same Azure authenticated instance between threads...

Or is it premature-optimization attempt on my side and Azure class is fine to instantiate in each service call that want to access Azure?

**Comment by weidongxu-microsoft** [comment]
> **Query/Question**
> In my service that is managing Azure resources on behalf of it's user, I'm obtaining azure endpoint like this:
> 
> ```
> Azure azure = Azure.configure()
>                 .withLogLevel(logLevel)
>                 .authenticate(credentials)
>                 .withSubscription(subscriptionId);
> ```
> 
> We estimate to have like 100 accounts with different creds/subscription id.
> 
> Can/should this Azure instance be cached in between calls and what's correct cache evict strategy (how long should one authenticated Azure client be cached)? I assume it is safe to share same Azure authenticated instance between threads...
> 
> Or is it premature-optimization attempt on my side and Azure class is fine to instantiate in each service call that want to access Azure?

Azure object created with
```
Azure azure = Azure.configure()
                .withLogLevel(logLevel)
                .authenticate(credentials)
                .withSubscription(subscriptionId);
```
will not initiate REST call at this stage. It only load the credential from file to Azure object. So there is very lost cost with it (compared to subsequent query/management method that would incur a REST API call).

You can verify this independently with log level set to LogLevel.BODY_AND_HEADERS and observe the logging.

In my profiling, the above code typically cost 20 milliseconds, while any subsequent query/management method takes 200 milliseconds to a few seconds.
Therefore in my opinion there is little benefit to cache Azure object. It is more nature to create Azure object, do a batch of query/management with it, then discard it when finished.

Please do not share Azure object across threads. There is no thread-safety guarantee on it and its nested resources.

**Comment by vihanp** [comment]
Thank you for your response.
