### ISSUE TITLE
[FEATURE REQ] Update batch swagger to the latest

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-libraries-for-java#817]
- [x] Java
- [ ] dotNet

**Comment by bgklein** [comment]
Can we get a status update on this?

**Comment by yaohaizh** [comment]
https://github.com/Azure/azure-libraries-for-java/pull/836 under code review should be ready soon@xccc-msft

**Comment by xccc-msft** [comment]
version 1.27
