### ISSUE TITLE
[BUG] The api-version '2018-02-14-preview' is invalid. 

### ISSUE THREAD

**Issue by pelegrim** [Azure/azure-libraries-for-java#818]
Current apiVersion is not supported.

Status code 400, {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2018-02-14-preview' is invalid. The supported versions are '2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}

https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/implementation/KeyVaultManagementClientImpl.java

**Comment by pelegrim** [comment]
https://github.com/Azure/azure-libraries-for-java/pull/819

**Comment by weidongxu-microsoft** [comment]
@pelegrim Would you let us know which operation would result in this exception?
I make a quick test and seems basic operation is good.

If there is issue with 2018-02-14-preview API, we would do the upgrade (However it would involve more than changing the version. Class/method need to be upgraded with that API).

```
PUT https://management.azure.com/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.KeyVault/vaults/kvweidxu?api-version=2018-02-14-preview

{"id":"/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.KeyVault/vaults/kvweidxu","name":"kvweidxu","type":"Microsoft.KeyVault/vaults","location":"eastus","tags":{},"properties":{"sku":{"family":"A","name":"standard"},"tenantId":"72f988bf-86f1-41af-91ab-2d7cd011db47","accessPolicies":[],"enabledForDeployment":false,"vaultUri":"https://kvweidxu.vault.azure.net","provisioningState":"RegisteringDns"}}
```

**Comment by pelegrim** [comment]
Hi,

It is myne mistake - different resource call

GET https://management.azure.com/subscriptions/{{subscriptionId}}/resources?$filter=resourceType eq 'Microsoft.KeyVault/vaults'&api-version=2018-02-14-preview

{
    "error": {
        "code": "InvalidApiVersionParameter",
        "message": "The api-version '2018-02-14-preview' is invalid. The supported versions are '2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
    }
}

**Comment by pelegrim** [comment]
Error exists if resourceGroups has empty value

GET  https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/<EMPTY>/providers/Microsoft.KeyVault/vaults?api-version=2018-02-14-preview

{
    "error": {
        "code": "InvalidApiVersionParameter",
        "message": "The api-version '2018-02-14-preview' is invalid. The supported versions are '2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
    }
}
