### ISSUE TITLE
[FEATURE REQ] Add https proble for network load balander

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-libraries-for-java#827]
- [x] Java
-  [x] .Net

**Comment by manurbek** [comment]
Please add WithProtocol(protocol_type) method called on LoadBalancer.DefineHttpProbe() that takes in a single parameter (i.e. protocol type: https, http) and sets the protocol of the probe to a specified protocol_type. Please make sure to support HTTPS protocol.

**Comment by weidongxu-microsoft** [comment]
Sample code (.NET).
By default the Port is 443.

```
                    loadBalancer.Update()
                        .DefineHttpsProbe(probeName2)
                            .WithRequestPath("/")
                            .Attach()
                        .Apply();
```

Note LoadBalancer SKU need to be LoadBalancerSkuType.Standard to support HTTPS probe. (Basic does not)

**Comment by manurbek** [comment]
Looks great. Which release will it be coming with?

**Comment by weidongxu-microsoft** [comment]
@manurbek
It will definitely with 1.27, which scheduled for Oct. 11th. Let us know if you need a urgent release say 1.26.1 (I assume you need only .NET? Meaning Java would still go standard 1.27 release).

**Comment by manurbek** [comment]
@weidongxu-microsoft We do need an urgent release of this feature as discussed earlier with Yaohai. What would be a realistic date for 1.26.1 release? 

Yes, we need it only in .NET sdk.

**Comment by weidongxu-microsoft** [comment]
@manurbek I will check with Yaohai. I assume early next week.

**Comment by manurbek** [comment]
@weidongxu-microsoft Thank you. Early next week would be perfect.

**Comment by weidongxu-microsoft** [comment]
@manurbek .NET 1.26.1 release.

**Comment by manurbek** [comment]
Thank you very much!
