### ISSUE TITLE
Proxy is not propagated in ProviderRegistrationInterceptor

### ISSUE THREAD

**Issue by malkochoglu** [Azure/azure-libraries-for-java#84]
Hi,
I am in a corp network and have to use Proxy. As far as I see even I set the proxy at the beginning using .withProxy, it is not propagated in the ProviderRegistrationInterceptor's intercept method. RestClient which is created in this block does not have proxy anymore on it. 

            if (cloudError != null && "MissingSubscriptionRegistration".equals(cloudError.code())) {
                Pattern pattern = Pattern.compile("/subscriptions/([\\w-]+)/", Pattern.CASE_INSENSITIVE);
                Matcher matcher = pattern.matcher(chain.request().url().toString());
                matcher.find();
                RestClient restClient = new RestClient.Builder()
                        .withBaseUrl("https://" + chain.request().url().host())
                        .withCredentials(credentials)
                        .withSerializerAdapter(jacksonAdapter)
                        .withResponseBuilderFactory(new AzureResponseBuilder.Factory())
                        .build();
                ResourceManager resourceManager = ResourceManager.authenticate(restClient)
                        .withSubscription(matcher.group(1));
                pattern = Pattern.compile(".*'(.*)'");
                matcher = pattern.matcher(cloudError.message());
                matcher.find();
                Provider provider = registerProvider(matcher.group(1), resourceManager);
                while (provider.registrationState().equalsIgnoreCase("Unregistered")
                        || provider.registrationState().equalsIgnoreCase("Registering")) {
                    SdkContext.sleep(5 * 1000);
                    provider = resourceManager.providers().getByName(provider.namespace());
                }
                // Retry
                response = chain.proceed(chain.request());
            }

**Comment by xccc-msft** [comment]
Hi @malkochoglu we will plan to support this.
