### ISSUE TITLE
[Change authgen.py to use API instead CLIs]

### ISSUE THREAD

**Issue by MourIdri** [Azure/azure-libraries-for-java#842]
Hi, 
In the following directory : https://github.com/Azure/azure-libraries-for-java/tree/master/tools the script in the file : authgen.py use Command Lines to create an SP and is getting data from Command Lines STDOUT.
COuld we use API instead ?  
in the following : 

```
p = subprocess.Popen('az ad sp create-for-rbac -o json --query "{client: appId, key: password, tenant: tenant}"', shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
p.wait()
out = p.stdout.read()

```
in terms of security , if someone adds a ">" security informations for the SP would be stored locally...

**Comment by xccc-msft** [comment]
Hi @MourIdri please check below link if it helps:
[you can login to Java SDK through other ways of authentication and create an auth file by following this sample](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-samples/src/main/java/com/microsoft/azure/management/graphrbac/samples/ManageServicePrincipal.java)

**Comment by MourIdri** [comment]
@xccc-msft, thanks for your answer.

But this is the official SDK there...

**Comment by xccc-msft** [comment]
@MourIdri Do you use the script output with ApplicationTokenCredentials?

**Comment by yaohaizh** [comment]
Close this as it only used for samples.
