### ISSUE TITLE
[QUERY] When will support for Regions in South Afria and Germany West Central become available

### ISSUE THREAD

**Issue by vaibhaw-** [Azure/azure-libraries-for-java#862]
**Query/Question**
We are unable to provision resources in Germany West Central region and the South Africa regions because the library doesn't support it yet. Can you provide us an ETA for their support so that we can plan accordingly?

***Why is this not a Bug or a feature Request?***
Bug - nothing that doesn't work as expected.
feature request - Isn't really a feature, it is must have - only a matter of time before you add the code for it.

**Setup (please complete the following information if applicable):**
NA
 
 **Information Checklist**

**Comment by weidongxu-microsoft** [comment]
As temporary workaround, you can do `Region.Create("southafricanorth")`.

**Comment by vaibhaw-** [comment]
Thanks for replying to quickly. I guess that will have to do for now. Is there an ETA in general for when it will become available?

**Comment by weidongxu-microsoft** [comment]
@vaibhaw- 

Next release is 1.27.1 which is scheduled on Oct. 25th. I will try to put the fix there. I will update after code ready.

**Comment by vaibhaw-** [comment]
Thanks! :)

**Comment by weidongxu-microsoft** [comment]
Fixed in [**1.27.2**](https://github.com/Azure/azure-libraries-for-java/releases/tag/v1.27.2).
