### ISSUE TITLE
[FEATURE REQ] Support config minTLSVersion while creating app services

### ISSUE THREAD

**Issue by Flanker32** [Azure/azure-libraries-for-java#887]
**Is your feature request related to a problem? Please describe.**
For now app service sdk didn't support speicfy some attributes(like miniTLSVersion) when creating new resources, which may block user creating resources with policy.
Related with https://github.com/microsoft/azure-maven-plugins/issues/876

**Describe the solution you'd like**
Support config siteConfig while creating app services, for instance, add method `withSiteConfig(SiteConfig)`

**Describe alternatives you've considered**
Support more attributes in interfact `WithSiteConfigs<FluentT>`

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by weidongxu-microsoft** [comment]
Fixed in 1.29. To be released on Dec. 8th.
