### ISSUE TITLE
Extend the 'ISqlServer' interface with 'Status' property.

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-libraries-for-java#9]
_From @olegburov on June 16, 2017 22:30_

Could you please extend the `Microsoft.Azure.Management.Sql.Fluent.ISqlServer` interface with `Status` property, just like `ISqlDatabase` has?

``` C#
namespace Microsoft.Azure.Management.Sql.Fluent
{
  ...
  public interface ISqlDatabase  : ... 
  {
  ... 
    /// <summary>
    /// Gets the status of the Azure SQL Server.
    /// </summary>
    string Status { get; }
  }  
}
```

Using [Azure Management Libraries for .NET](https://www.nuget.org/packages/Microsoft.Azure.Management.Fluent/) (aka Fluent API) I want to get a status of my Azure SQL Server like this:

``` C#
  var credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal(clientId, clientSecret, tenantId, AzureEnvironment.AzureGlobalCloud);
        
  var azure = Azure
    .Configure()
    .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
    .Authenticate(credentials)
    .WithSubscription(subscriptionId);

  var sqlServer = azure.SqlServers.GetById("Sql-Server-Id-Here");
  var status = sqlServer.Status;
```

_Copied from original issue: Azure/azure-sdk-for-net#3386_

**Comment by milismsft** [comment]
https://github.com/Azure/azure-libraries-for-java/pull/196 adresses this issue.
