### ISSUE TITLE
[BUG] Generic Resources tags do not appear to be populated after retrieval

### ISSUE THREAD

**Issue by paulojohnj** [Azure/azure-libraries-for-java#905]
**Describe the bug**
After retrieving a list of generic resources by a single tag, the `.tags()` method appears to always return an empty set, even on resources that have tags.

***Exception or Stack Trace***
No exception or trace as the behavior is not a failure.

**To Reproduce**
1 tag a resource with multiple tags 
2 retrieve generic resources by one of those tags
3 attempt to list the tags on any of the retrieved resources

***Code Snippet***
Add the code snippet that causes the issue.

```
    public Set<GenericResource> getResourcesByTags(final String resourceGroupName, final Map<String, String> tags) {
        final Entry<String, String> entry = tags.entrySet().iterator().next();
        final PagedList<GenericResource> resources = this.client.genericResources().listByTag(resourceGroupName, entry.getKey(),
                entry.getValue());
        resources.loadAll();
        
        for(final GenericResource gr : resources) {
            LOGGER.info("tags: {}", gr.tags());
        }
```

**Expected behavior**
I would expect the returned generic resources to have their tags collection populated

**Setup (please complete the following information):**
 - OS: [e.g. iOS] macOS Mojave
 - IDE : [e.g. IntelliJ] Eclipse 2019
 - Version of the Library used 1.28.0

**Additional context**
If this is not how the generic resources queries were intended to work, is there another method to list all resources with a particular set of tags

**Comment by leylakazemi** [comment]
Thank you for reporting this. This is a limitation of our current API. You cannot retrieve the list of tags on the resources that are returned which had a particular tag. We have this in our backlog. We will try to prioritize this.

**Comment by kenieva** [comment]
This feature request is accounted for and is in the backlog. We will comment once it is completed.
