### ISSUE TITLE
[BUG] SDK will override users' app settings when create new functions

### ISSUE THREAD

**Issue by Flanker32** [Azure/azure-libraries-for-java#915]
**Describe the bug**
SDK will override users' app settings(`AzureWebJobsStorage`,`AzureWebJobsDashboard`) when create new functions as SDK will create storage account asynchronous and overwrite the appsetting once storage account created

**To Reproduce**

Create function with fluent SDK and define `AzureWebJobsStorage` or `AzureWebJobsDashboard` before execute `create()`

***Code Snippet***
``` java
    protected void createFunctionApp() throws AzureAuthFailureException, MojoExecutionException 
    {
        ...
        final FunctionRuntimeHandler runtimeHandler = getFunctionRuntimeHandler();
        final WithCreate withCreate = runtimeHandler.defineAppWithRuntime();
        configureAppSettings(withCreate::withAppSettings, getAppSettingsWithDefaultValue());
        withCreate.withJavaVersion(DEFAULT_JAVA_VERSION).withWebContainer(null).create();
        ...
    }

    protected void configureAppSettings(final Consumer<Map> withAppSettings, final Map appSettings) {
        if (appSettings != null && !appSettings.isEmpty()) {
            withAppSettings.accept(appSettings);
        }
    }
```

**Expected behavior**
Use `AzureWebJobsStorage` and `AzureWebJobsDashboard` specified by users

**Setup (please complete the following information):**
 - OS:  Windows 10
 - IDE : IntelliJ 2019.2
 - Version of the Library used : 1.28.0

**Additional context**
SDK could check whether those app settings exists before deploy and update it once user didn't set it.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by yaohaizh** [comment]
@weidongxu-microsoft could you help take a look at this issue?
