### ISSUE TITLE
[FEATURE REQ] Make test pipeline to adopt the track 2 common practice

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-libraries-for-java#986]
There should be two main items needed here: 
- [ ] Upgrade the unit test framework to 5 if needed
- [ ] Make the test cases run in parallel

**Comment by yungezz** [comment]
we'll move repo to azure-sdk-for-java, let's work on it during the moving.

**Comment by weidongxu-microsoft** [comment]
I think this one is largely solved.

1. junit 5 is converted when we migrate each service
2. parrallel is converted when migrate (do not use static variable, set sdkContext from TestBase to all azure management clients).

**Comment by yungezz** [comment]
nice, will close it then.
